# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='downbanner',
            name='active_code',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sidebanner',
            name='active_code',
            field=models.BooleanField(default=False),
        ),
    ]
