# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0002_auto_20170502_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downbanner',
            name='code',
            field=models.TextField(blank=True, null=True, verbose_name='\u041a\u043e\u0434 \u0431\u0430\u043d\u043d\u0435\u0440\u0430'),
        ),
        migrations.AlterField(
            model_name='downbanner',
            name='link',
            field=models.URLField(blank=True, help_text='http://example.com', null=True, verbose_name='\u0421\u0441\u044b\u043b\u043a\u0430'),
        ),
        migrations.AlterField(
            model_name='sidebanner',
            name='code',
            field=models.TextField(blank=True, null=True, verbose_name='\u041a\u043e\u0434 \u0431\u0430\u043d\u043d\u0435\u0440\u0430'),
        ),
        migrations.AlterField(
            model_name='sidebanner',
            name='link',
            field=models.URLField(blank=True, help_text='http://example.com', null=True, verbose_name='\u0421\u0441\u044b\u043b\u043a\u0430'),
        ),
    ]
