# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='time',
            field=models.TimeField(blank=True, null=True, verbose_name='\u0412\u0440\u0435\u043c\u044f'),
        ),
    ]
