# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 00:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_auto_20170427_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435'),
        ),
        migrations.AlterField(
            model_name='videos',
            name='time',
            field=models.TimeField(blank=True, help_text='\u0444\u043e\u0440\u043c\u0430\u0442 00:11:22', null=True, verbose_name='\u0412\u0440\u0435\u043c\u044f'),
        ),
    ]
