# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-12 01:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='group',
            field=models.IntegerField(choices=[(1, '\u0421\u0443\u043f\u0435\u0440 \u0430\u0434\u043c\u0438\u043d\u0438\u0441\u0442\u0440\u0430\u0442\u043e\u0440'), (2, '\u0410\u0434\u043c\u0438\u043d\u0438\u0441\u0442\u0440\u0430\u0442\u043e\u0440')], verbose_name='\u0413\u0440\u0443\u043f\u0430'),
        ),
    ]
