# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-12 11:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_merge_20170512_1411'),
        ('users', '0003_merge_20170512_0457'),
    ]

    operations = [
    ]
