# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 23:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20170329_0156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, default=1, max_length=40, verbose_name='\u0418\u043c\u044f'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, default=1, max_length=40, verbose_name='\u0424\u0430\u043c\u0438\u043b\u0438\u044f'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='middle_name',
            field=models.CharField(blank=True, default=1, max_length=40, verbose_name='\u041e\u0442\u0447\u0435\u0441\u0442\u0432\u043e'),
            preserve_default=False,
        ),
    ]
