# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 02:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20170329_0250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default=1, upload_to='user/avatar', verbose_name='\u0410\u0432\u0430\u0442\u0430\u0440'),
            preserve_default=False,
        ),
    ]
