# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-28 22:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='description',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='keywords',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='title',
        ),
        migrations.RemoveField(
            model_name='sections',
            name='description',
        ),
        migrations.RemoveField(
            model_name='sections',
            name='keywords',
        ),
        migrations.RemoveField(
            model_name='sections',
            name='title',
        ),
        migrations.AddField(
            model_name='articles',
            name='SEODescription',
            field=models.TextField(blank=True, null=True, verbose_name='SEO Description'),
        ),
        migrations.AddField(
            model_name='articles',
            name='SEOKeywords',
            field=models.TextField(blank=True, null=True, verbose_name='SEO Keywords'),
        ),
        migrations.AddField(
            model_name='articles',
            name='SEOTitle',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='SEO Title'),
        ),
        migrations.AddField(
            model_name='sections',
            name='SEODescription',
            field=models.TextField(blank=True, null=True, verbose_name='SEO Description'),
        ),
        migrations.AddField(
            model_name='sections',
            name='SEOKeywords',
            field=models.TextField(blank=True, null=True, verbose_name='SEO Keywords'),
        ),
        migrations.AddField(
            model_name='sections',
            name='SEOTitle',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='SEO Title'),
        ),
    ]
