# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-28 22:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20170529_0111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articles',
            old_name='heading',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='sections',
            old_name='heading',
            new_name='title',
        ),
    ]
