# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 00:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20170529_0112'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='title_image',
            field=models.ImageField(blank=True, upload_to='background/%Y/%m/%d/', verbose_name='\u0424\u043e\u0442\u043e \u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a'),
        ),
    ]
