# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-11 19:46
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20170309_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='sections',
            name='content',
            field=ckeditor.fields.RichTextField(default=1),
            preserve_default=False,
        ),
    ]
