# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-28 16:26
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20170602_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='\u041a\u043e\u043d\u0442\u0435\u043d\u0442'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='\u0414\u0430\u0442\u0430 \u0441\u043e\u0437\u0434\u0430\u043d\u0438\u044f'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='image',
            field=models.ImageField(blank=True, upload_to='articles/%Y/%m/%d/', verbose_name='\u0424\u043e\u0442\u043e'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='sections',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='articles.Sections', verbose_name='\u0420\u0443\u0431\u0440\u0438\u043a\u0430'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='title',
            field=models.TextField(blank=True, null=True, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='title_image',
            field=models.ImageField(blank=True, upload_to='background/%Y/%m/%d/', verbose_name='\u0424\u043e\u0442\u043e \u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='\u0414\u0430\u0442\u0430 \u0440\u0435\u0434\u0430\u043a\u0442\u0438\u0440\u043e\u0432\u0430\u043d\u0438\u044f'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='video',
            field=models.TextField(blank=True, verbose_name='\u041a\u043e\u0434 \u0432\u0438\u0434\u0435\u043e'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='views',
            field=models.IntegerField(default=0, verbose_name='\u041f\u0440\u043e\u0441\u043c\u043e\u0442\u0440\u044b'),
        ),
        migrations.AlterField(
            model_name='sections',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='\u041a\u043e\u043d\u0442\u0435\u043d\u0442'),
        ),
        migrations.AlterField(
            model_name='sections',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='\u0414\u0430\u0442\u0430 \u0441\u043e\u0437\u0434\u0430\u043d\u0438\u044f'),
        ),
        migrations.AlterField(
            model_name='sections',
            name='name',
            field=models.CharField(max_length=150, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435'),
        ),
        migrations.AlterField(
            model_name='sections',
            name='title',
            field=models.TextField(blank=True, null=True, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a'),
        ),
        migrations.AlterField(
            model_name='sections',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='\u0414\u0430\u0442\u0430 \u0440\u0435\u0434\u0430\u043a\u0442\u0438\u0440\u043e\u0432\u0430\u043d\u0438\u044f'),
        ),
    ]
