# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-11 20:04
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20170311_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sections',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='\u041a\u043e\u043d\u0442\u0435\u043d\u0442'),
        ),
    ]
