# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-11 20:24
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_auto_20170311_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sections',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='\u041a\u043e\u043d\u0442\u0435\u043d\u0442'),
        ),
    ]
