# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-12 00:39
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_auto_20170311_2024'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='\u0414\u0430\u0442\u0430 \u0441\u043e\u0437\u0434\u0430\u043d\u0438\u044f')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, null=True, unique=True, verbose_name='URL')),
                ('title', models.CharField(max_length=150, verbose_name='Title')),
                ('keywords', models.TextField(blank=True, null=True, verbose_name='Keywords')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('heading', models.TextField(blank=True, null=True, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='\u041a\u043e\u043d\u0442\u0435\u043d\u0442')),
                ('video', models.TextField(blank=True, verbose_name='\u041a\u043e\u0434 \u0432\u0438\u0434\u0435\u043e')),
                ('image', models.ImageField(blank=True, upload_to='articles/%Y/%m/%d/', verbose_name='\u0424\u043e\u0442\u043e')),
            ],
        ),
        migrations.AlterModelOptions(
            name='sections',
            options={'ordering': ('id',), 'verbose_name': '\u0420\u0443\u0431\u0440\u0438\u043a\u0430', 'verbose_name_plural': '\u0420\u0443\u0431\u0440\u0438\u043a\u0438'},
        ),
        migrations.AlterField(
            model_name='sections',
            name='name',
            field=models.CharField(max_length=150, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435'),
        ),
        migrations.AddField(
            model_name='articles',
            name='sections',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='articles.Sections', verbose_name='\u0420\u0443\u0431\u0440\u0438\u043a\u0430'),
        ),
    ]
