# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-19 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('UAH', '\u0433\u0440\u043d'), ('RUB', '\u0440\u0443\u0431'), ('KZT', '\u0442\u043d\u0433')], max_length=3, verbose_name='\u0412\u0430\u043b\u044e\u0442\u0430')),
            ],
            options={
                'verbose_name': 'Site Configuration',
            },
        ),
    ]
