# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(blank=True, choices=[('UAH', '\u0433\u0440\u043d'), ('RUB', '\u0440\u0443\u0431'), ('KZT', '\u0442\u043d\u0433')], max_length=3, verbose_name='\u0412\u0430\u043b\u044e\u0442\u0430')),
                ('dollar_rate', models.FloatField(blank=True, null=True, verbose_name='\u041a\u0443\u0440\u0441 \u0434\u043e\u043b\u043b\u0430\u0440\u0430')),
            ],
            options={
                'verbose_name': 'Site Configuration',
            },
        ),
        migrations.CreateModel(
            name='StaticPageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('\u0413\u043b\u0430\u0432\u043d\u0430\u044f', '\u0413\u043b\u0430\u0432\u043d\u0430\u044f'), ('\u041d\u043e\u0432\u043e\u0441\u0442\u0440\u043e\u0438', '\u041d\u043e\u0432\u043e\u0441\u0442\u0440\u043e\u0438'), ('\u041f\u043e\u0441\u0443\u0442\u043e\u0447\u043d\u0430', '\u041f\u043e\u0441\u0443\u0442\u043e\u0447\u043d\u0430'), ('\u041a\u0432\u0430\u0440\u0442\u0438\u0440\u044b \u0438 \u0414\u043e\u043c\u0430', '\u041a\u0432\u0430\u0440\u0442\u0438\u0440\u044b \u0438 \u0414\u043e\u043c\u0430'), ('\u041e\u0444\u0438\u0441\u044b \u0438 \u043c\u0430\u0433\u0430\u0437\u0438\u043d\u044b', '\u041e\u0444\u0438\u0441\u044b \u0438 \u043c\u0430\u0433\u0430\u0437\u0438\u043d\u044b'), ('\u0414\u043e\u0432\u0435\u0440\u0435\u0435', '\u0414\u043e\u0432\u0435\u0440\u0435\u0435'), ('\u041a\u043e\u043d\u0442\u0430\u043a\u0442\u044b', '\u041a\u043e\u043d\u0442\u0430\u043a\u0442\u044b')], max_length=30, unique=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('title', models.TextField(blank=True, null=True, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a')),
                ('subtitle', models.TextField(blank=True, null=True, verbose_name='\u041f\u043e\u0434\u0437\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a')),
                ('SEOTitle', models.TextField(blank=True, null=True, verbose_name='SEO Title')),
                ('SEOKeywords', models.TextField(blank=True, null=True, verbose_name='SEO Keywords')),
                ('SEODescription', models.TextField(blank=True, null=True, verbose_name='SEO Description')),
                ('is_enable', models.BooleanField(default=True, verbose_name='\u0412\u043a\u043b\u044e\u0447\u0435\u043d \u043b\u0438?')),
            ],
            options={
                'ordering': ('name',),
                'verbose_name': '\u0421\u0442\u0430\u0442\u0438\u0447\u0435\u0441\u043a\u0430\u044f \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u0430',
                'verbose_name_plural': '\u0421\u0442\u0430\u0442\u0438\u0447\u0435\u0441\u043a\u0438\u0435 \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u0438',
            },
        ),
    ]
