# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 03:51
from __future__ import unicode_literals

import admin2.models
import ckeditor_uploader.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingPageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='\u041a\u0432\u0430\u0440\u0442\u0438\u0440\u044b \u0438 \u0414\u043e\u043c\u0430', editable=False, max_length=30, unique=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('slug', models.SlugField(allow_unicode=True, default='\u043a\u0432\u0430\u0440\u0442\u0438\u0440\u044b-\u0438-\u0434\u043e\u043c\u0430', editable=False, validators=[admin2.models.slug_validator], verbose_name='URL')),
                ('title', models.TextField(blank=True, null=True, verbose_name='SEO \u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a')),
                ('subtitle', models.TextField(blank=True, null=True, verbose_name='\u041f\u043e\u0434\u0437\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a')),
                ('SEOTitle', models.TextField(blank=True, null=True, verbose_name='SEO Title')),
                ('SEOKeywords', models.TextField(blank=True, null=True, verbose_name='SEO Keywords')),
                ('SEODescription', models.TextField(blank=True, null=True, verbose_name='SEO Description')),
                ('is_enable', models.BooleanField(default=True, verbose_name='\u0412\u043a\u043b\u044e\u0447\u0435\u043d\u0430 \u043b\u0438 \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u0430?')),
                ('image', models.ImageField(blank=True, upload_to='background/%Y/%m/%d/', verbose_name='\u0424\u043e\u0442\u043e')),
                ('image_seo', models.ImageField(blank=True, upload_to='seo/%Y/%m/%d/', verbose_name='\u0424\u043e\u0442\u043e SEO')),
                ('title_h1', models.TextField(blank=True, null=True, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a H1')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='\u041a\u043e\u043d\u0442\u0435\u043d\u0442')),
            ],
            options={
                'verbose_name': '\u041a\u0432\u0430\u0440\u0442\u0438\u0440\u044b \u0438 \u0414\u043e\u043c\u0430',
            },
        ),
        migrations.CreateModel(
            name='ContactPageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='\u041a\u043e\u043d\u0442\u0430\u043a\u0442\u044b', editable=False, max_length=30, unique=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('slug', models.SlugField(allow_unicode=True, default='\u043a\u043e\u043d\u0442\u0430\u043a\u0442\u044b', editable=False, validators=[admin2.models.slug_validator], verbose_name='URL')),
                ('title', models.TextField(blank=True, null=True, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a')),
                ('subtitle', models.TextField(blank=True, null=True, verbose_name='\u041f\u043e\u0434\u0437\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a')),
                ('SEOTitle', models.TextField(blank=True, null=True, verbose_name='SEO Title')),
                ('SEOKeywords', models.TextField(blank=True, null=True, verbose_name='SEO Keywords')),
                ('SEODescription', models.TextField(blank=True, null=True, verbose_name='SEO Description')),
                ('image', models.ImageField(blank=True, upload_to='background/%Y/%m/%d/', verbose_name='\u0424\u043e\u0442\u043e')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('our_address', models.CharField(blank=True, max_length=250, null=True, verbose_name='\u041d\u0430\u0448 \u0430\u0434\u0440\u0435\u0441')),
                ('our_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('phone', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u0422\u0435\u043b\u0435\u0444\u043e\u043d')),
            ],
            options={
                'verbose_name': '\u041a\u043e\u043d\u0442\u0430\u043a\u0442\u044b',
            },
        ),
        migrations.CreateModel(
            name='DailyPageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='\u041f\u043e\u0441\u0443\u0442\u043e\u0447\u043d\u0430', editable=False, max_length=30, unique=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('slug', models.SlugField(allow_unicode=True, default='\u043f\u043e\u0441\u0443\u0442\u043e\u0447\u043d\u0430', editable=False, validators=[admin2.models.slug_validator], verbose_name='URL')),
                ('title', models.TextField(blank=True, null=True, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a')),
                ('subtitle', models.TextField(blank=True, null=True, verbose_name='\u041f\u043e\u0434\u0437\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a')),
                ('SEOTitle', models.TextField(blank=True, null=True, verbose_name='SEO Title')),
                ('SEOKeywords', models.TextField(blank=True, null=True, verbose_name='SEO Keywords')),
                ('SEODescription', models.TextField(blank=True, null=True, verbose_name='SEO Description')),
                ('is_enable', models.BooleanField(default=True, verbose_name='\u0412\u043a\u043b\u044e\u0447\u0435\u043d\u0430 \u043b\u0438 \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u0430?')),
                ('image', models.ImageField(blank=True, upload_to='background/%Y/%m/%d/', verbose_name='\u0424\u043e\u0442\u043e')),
                ('image_seo', models.ImageField(blank=True, upload_to='seo/%Y/%m/%d/', verbose_name='\u0424\u043e\u0442\u043e SEO')),
                ('title_h1', models.TextField(blank=True, null=True, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a H1')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='\u041a\u043e\u043d\u0442\u0435\u043d\u0442')),
            ],
            options={
                'verbose_name': '\u041f\u043e\u0441\u0443\u0442\u043e\u0447\u043d\u0430',
            },
        ),
        migrations.CreateModel(
            name='EarthPageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='\u0417\u0435\u043c\u043b\u044f', editable=False, max_length=30, unique=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('slug', models.SlugField(allow_unicode=True, default='\u0437\u0435\u043c\u043b\u044f', editable=False, validators=[admin2.models.slug_validator], verbose_name='URL')),
                ('title', models.TextField(blank=True, null=True, verbose_name='SEO \u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a')),
                ('subtitle', models.TextField(blank=True, null=True, verbose_name='\u041f\u043e\u0434\u0437\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a')),
                ('SEOTitle', models.TextField(blank=True, null=True, verbose_name='SEO Title')),
                ('SEOKeywords', models.TextField(blank=True, null=True, verbose_name='SEO Keywords')),
                ('SEODescription', models.TextField(blank=True, null=True, verbose_name='SEO Description')),
                ('is_enable', models.BooleanField(default=True, verbose_name='\u0412\u043a\u043b\u044e\u0447\u0435\u043d\u0430 \u043b\u0438 \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u0430?')),
                ('image', models.ImageField(blank=True, upload_to='background/%Y/%m/%d/', verbose_name='\u0424\u043e\u0442\u043e')),
                ('image_seo', models.ImageField(blank=True, upload_to='seo/%Y/%m/%d/', verbose_name='\u0424\u043e\u0442\u043e SEO')),
                ('title_h1', models.TextField(blank=True, null=True, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a H1')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='\u041a\u043e\u043d\u0442\u0435\u043d\u0442')),
            ],
            options={
                'verbose_name': '\u0417\u0435\u043c\u043b\u044f',
            },
        ),
        migrations.CreateModel(
            name='IndexPageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='\u0413\u043b\u0430\u0432\u043d\u0430\u044f', editable=False, max_length=30, unique=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('slug', models.SlugField(allow_unicode=True, default='\u0433\u043b\u0430\u0432\u043d\u0430\u044f', editable=False, validators=[admin2.models.slug_validator], verbose_name='URL')),
                ('title', models.TextField(blank=True, null=True, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a')),
                ('subtitle', models.TextField(blank=True, null=True, verbose_name='\u041f\u043e\u0434\u0437\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a')),
                ('SEOTitle', models.TextField(blank=True, null=True, verbose_name='SEO Title')),
                ('SEOKeywords', models.TextField(blank=True, null=True, verbose_name='SEO Keywords')),
                ('SEODescription', models.TextField(blank=True, null=True, verbose_name='SEO Description')),
                ('image', models.ImageField(blank=True, upload_to='background/%Y/%m/%d/', verbose_name='\u0424\u043e\u0442\u043e')),
                ('image_seo', models.ImageField(blank=True, upload_to='seo/%Y/%m/%d/', verbose_name='\u0424\u043e\u0442\u043e SEO')),
                ('title_h1', models.TextField(blank=True, null=True, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a H1')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='\u041a\u043e\u043d\u0442\u0435\u043d\u0442')),
            ],
            options={
                'verbose_name': '\u0413\u043b\u0430\u0432\u043d\u0430\u044f',
            },
        ),
        migrations.CreateModel(
            name='NewBuildingPageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='\u041d\u043e\u0432\u043e\u0441\u0442\u0440\u043e\u0438', editable=False, max_length=30, unique=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('slug', models.SlugField(allow_unicode=True, default='\u043d\u043e\u0432\u043e\u0441\u0442\u0440\u043e\u0438', editable=False, validators=[admin2.models.slug_validator], verbose_name='URL')),
                ('title', models.TextField(blank=True, null=True, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a')),
                ('subtitle', models.TextField(blank=True, null=True, verbose_name='\u041f\u043e\u0434\u0437\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a')),
                ('SEOTitle', models.TextField(blank=True, null=True, verbose_name='SEO Title')),
                ('SEOKeywords', models.TextField(blank=True, null=True, verbose_name='SEO Keywords')),
                ('SEODescription', models.TextField(blank=True, null=True, verbose_name='SEO Description')),
                ('is_enable', models.BooleanField(default=True, verbose_name='\u0412\u043a\u043b\u044e\u0447\u0435\u043d\u0430 \u043b\u0438 \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u0430?')),
                ('image', models.ImageField(blank=True, upload_to='background/%Y/%m/%d/', verbose_name='\u0424\u043e\u0442\u043e')),
                ('image_seo', models.ImageField(blank=True, upload_to='seo/%Y/%m/%d/', verbose_name='\u0424\u043e\u0442\u043e SEO')),
                ('title_h1', models.TextField(blank=True, null=True, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a H1')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='\u041a\u043e\u043d\u0442\u0435\u043d\u0442')),
            ],
            options={
                'verbose_name': '\u041d\u043e\u0432\u043e\u0441\u0442\u0440\u043e\u0438',
            },
        ),
        migrations.CreateModel(
            name='OfisPageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='\u041e\u0444\u0438\u0441\u044b \u0438 \u043c\u0430\u0433\u0430\u0437\u0438\u043d\u044b', editable=False, max_length=30, unique=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('slug', models.SlugField(allow_unicode=True, default='\u043e\u0444\u0438\u0441\u044b-\u0438-\u043c\u0430\u0433\u0430\u0437\u0438\u043d\u044b', editable=False, validators=[admin2.models.slug_validator], verbose_name='URL')),
                ('title', models.TextField(blank=True, null=True, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a')),
                ('subtitle', models.TextField(blank=True, null=True, verbose_name='\u041f\u043e\u0434\u0437\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a')),
                ('SEOTitle', models.TextField(blank=True, null=True, verbose_name='SEO Title')),
                ('SEOKeywords', models.TextField(blank=True, null=True, verbose_name='SEO Keywords')),
                ('SEODescription', models.TextField(blank=True, null=True, verbose_name='SEO Description')),
                ('is_enable', models.BooleanField(default=True, verbose_name='\u0412\u043a\u043b\u044e\u0447\u0435\u043d\u0430 \u043b\u0438 \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u0430?')),
                ('image', models.ImageField(blank=True, upload_to='background/%Y/%m/%d/', verbose_name='\u0424\u043e\u0442\u043e')),
                ('image_seo', models.ImageField(blank=True, upload_to='seo/%Y/%m/%d/', verbose_name='\u0424\u043e\u0442\u043e SEO')),
                ('title_h1', models.TextField(blank=True, null=True, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a H1')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='\u041a\u043e\u043d\u0442\u0435\u043d\u0442')),
            ],
            options={
                'verbose_name': '\u041e\u0444\u0438\u0441\u044b \u0438 \u043c\u0430\u0433\u0430\u0437\u0438\u043d\u044b',
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(blank=True, choices=[('UAH', '\u0433\u0440\u043d'), ('RUB', '\u0440\u0443\u0431'), ('KZT', '\u0442\u043d\u0433')], max_length=3, verbose_name='\u0412\u0430\u043b\u044e\u0442\u0430')),
                ('dollar_rate', models.FloatField(blank=True, null=True, verbose_name='\u041a\u0443\u0440\u0441 \u0434\u043e\u043b\u043b\u0430\u0440\u0430')),
                ('name_site', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0441\u0430\u0439\u0442\u0430')),
            ],
            options={
                'verbose_name': 'Site Configuration',
            },
        ),
        migrations.CreateModel(
            name='TrustPageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='\u0414\u043e\u0432\u0435\u0440\u0435\u0435', editable=False, max_length=30, unique=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('slug', models.SlugField(allow_unicode=True, default='\u0434\u043e\u0432\u0435\u0440\u0435\u0435', editable=False, validators=[admin2.models.slug_validator], verbose_name='URL')),
                ('title', models.TextField(blank=True, null=True, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a')),
                ('subtitle', models.TextField(blank=True, null=True, verbose_name='\u041f\u043e\u0434\u0437\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a')),
                ('SEOTitle', models.TextField(blank=True, null=True, verbose_name='SEO Title')),
                ('SEOKeywords', models.TextField(blank=True, null=True, verbose_name='SEO Keywords')),
                ('SEODescription', models.TextField(blank=True, null=True, verbose_name='SEO Description')),
                ('image', models.ImageField(blank=True, upload_to='background/%Y/%m/%d/', verbose_name='\u0424\u043e\u0442\u043e')),
                ('video', models.TextField(blank=True, verbose_name='\u041a\u043e\u0434 \u0432\u0438\u0434\u0435\u043e')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('faq_enable', models.BooleanField(default=True, verbose_name='\u0412\u043b\u044e\u0447\u0435\u043d \u043b\u0438 FAQ?')),
            ],
            options={
                'verbose_name': '\u0414\u043e\u0432\u0435\u0440\u0435\u0435',
            },
        ),
    ]
