# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-19 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='dollar_rate',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='\u041a\u0443\u0440\u0441 \u0434\u043e\u043b\u043b\u0430\u0440\u0430'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='currency',
            field=models.CharField(blank=True, choices=[('UAH', '\u0433\u0440\u043d'), ('RUB', '\u0440\u0443\u0431'), ('KZT', '\u0442\u043d\u0433')], max_length=3, verbose_name='\u0412\u0430\u043b\u044e\u0442\u0430'),
        ),
    ]
