# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-08 04:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '__first__'),
        ('admin2', '0002_contactpagemodel_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='name_site',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sites.Site', verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0441\u0430\u0439\u0442\u0430'),
        ),
    ]
