# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-08 06:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin2', '0003_auto_20170508_0752'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettingsAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u0412\u0430\u043b\u044e\u0442\u0430')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u0413\u043e\u0440\u043e\u0434')),
                ('city_plural', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u0413\u043e\u0440\u043e\u0434 (\u0440\u043e\u0434\u0438\u0442\u0435\u043b\u044c\u043d\u044b\u0439)')),
                ('address', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u0423\u043b\u0438\u0446\u0430')),
                ('email', models.EmailField(blank=True, max_length=50, null=True, verbose_name='Email')),
            ],
            options={
                'verbose_name': '\u0410\u0434\u0440\u0435\u0441\u0430',
            },
        ),
        migrations.AlterModelOptions(
            name='settings',
            options={'verbose_name': '\u0412\u0430\u043b\u044e\u0442\u0430'},
        ),
        migrations.RemoveField(
            model_name='settings',
            name='name_site',
        ),
    ]
