# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-19 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin2', '0003_auto_20170319_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='dollar_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='\u041a\u0443\u0440\u0441 \u0434\u043e\u043b\u043b\u0430\u0440\u0430'),
        ),
    ]
