# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-09 14:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin2', '0004_dailypagemodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staticpagemodel',
            options={'verbose_name': '\u0421\u0442\u0430\u0442\u0438\u0447\u0435\u0441\u043a\u0438\u0435 \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u0438'},
        ),
        migrations.RemoveField(
            model_name='staticpagemodel',
            name='SEODescription',
        ),
        migrations.RemoveField(
            model_name='staticpagemodel',
            name='SEOKeywords',
        ),
        migrations.RemoveField(
            model_name='staticpagemodel',
            name='SEOTitle',
        ),
        migrations.RemoveField(
            model_name='staticpagemodel',
            name='is_enable',
        ),
        migrations.RemoveField(
            model_name='staticpagemodel',
            name='name',
        ),
        migrations.RemoveField(
            model_name='staticpagemodel',
            name='subtitle',
        ),
        migrations.RemoveField(
            model_name='staticpagemodel',
            name='title',
        ),
    ]
