# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-09 14:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin2', '0005_auto_20170409_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticpagemodel',
            name='indexpagemodel',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='admin2.IndexPageModel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staticpagemodel',
            name='newbuildingpagemodel',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='admin2.NewBuildingPageModel'),
            preserve_default=False,
        ),
    ]
