# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-09 14:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin2', '0006_auto_20170409_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticpagemodel',
            name='indexpagemodel',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='admin2.IndexPageModel', verbose_name='\u0413\u043b\u0430\u0432\u043d\u0430\u044f'),
        ),
        migrations.AlterField(
            model_name='staticpagemodel',
            name='newbuildingpagemodel',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='admin2.NewBuildingPageModel', verbose_name='\u041d\u043e\u0432\u043e\u0441\u0442\u0440\u043e\u0438'),
        ),
    ]
