# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin2', '0006_staticpagemodel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticpagemodel',
            name='name',
            field=models.CharField(choices=[('\u0413\u043b\u0430\u0432\u043d\u0430\u044f', '\u0413\u043b\u0430\u0432\u043d\u0430\u044f'), ('\u041d\u043e\u0432\u043e\u0441\u0442\u0440\u043e\u0438', '\u041d\u043e\u0432\u043e\u0441\u0442\u0440\u043e\u0438'), ('\u041f\u043e\u0441\u0443\u0442\u043e\u0447\u043d\u0430', '\u041f\u043e\u0441\u0443\u0442\u043e\u0447\u043d\u0430'), ('\u041a\u0432\u0430\u0440\u0442\u0438\u0440\u044b \u0438 \u0414\u043e\u043c\u0430', '\u041a\u0432\u0430\u0440\u0442\u0438\u0440\u044b \u0438 \u0414\u043e\u043c\u0430'), ('\u041e\u0444\u0438\u0441\u044b \u0438 \u043c\u0430\u0433\u0430\u0437\u0438\u043d\u044b', '\u041e\u0444\u0438\u0441\u044b \u0438 \u043c\u0430\u0433\u0430\u0437\u0438\u043d\u044b'), ('\u0414\u043e\u0432\u0435\u0440\u0435\u0435', '\u0414\u043e\u0432\u0435\u0440\u0435\u0435'), ('\u041a\u043e\u043d\u0442\u0430\u043a\u0442\u044b', '\u041a\u043e\u043d\u0442\u0430\u043a\u0442\u044b')], default=1, max_length=30, unique=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435'),
            preserve_default=False,
        ),
    ]
