# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 23:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin2', '0007_auto_20170327_1844'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staticpagemodel',
            old_name='is_eneble',
            new_name='is_enable',
        ),
    ]
