# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-09 06:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('admin2', '0007_auto_20170509_0419'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettingsPrivate24',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant', models.IntegerField(blank=True, null=True, verbose_name='\u041f\u0440\u0438\u0432\u0430\u044224 merchant ID')),
                ('signature', models.IntegerField(blank=True, null=True, verbose_name='\u041f\u0440\u0438\u0432\u0435\u044224 signature')),
                ('currency', models.CharField(blank=True, choices=[('UAH', '\u0433\u0440\u043d'), ('RUB', '\u0440\u0443\u0431'), ('KZT', '\u0442\u043d\u0433')], max_length=3, verbose_name='\u0412\u0430\u043b\u044e\u0442\u0430')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='activefranchise',
            name='active_franchise',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='\u0424\u0440\u0430\u043d\u0448\u0438\u0437\u0430 \u0430\u043a\u0442\u0438\u0432\u043d\u0430 \u0434\u043e'),
        ),
    ]
