# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-09 14:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin2', '0008_auto_20170409_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticpagemodel',
            name='dailypagemodel',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='admin2.DailyPageModel', verbose_name='\u041f\u043e\u0441\u0443\u0442\u043e\u0447\u043d\u0430'),
            preserve_default=False,
        ),
    ]
