# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-09 06:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin2', '0008_auto_20170509_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settingsprivate24',
            name='signature',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='\u041f\u0440\u0438\u0432\u0435\u044224 signature'),
        ),
    ]
