# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-10 00:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin2', '0009_auto_20170509_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settingsprivate24',
            name='currency',
            field=models.CharField(blank=True, choices=[('UAH', 'UAH'), ('RUB', 'RUB'), ('USD', 'USD')], max_length=3, verbose_name='\u0412\u0430\u043b\u044e\u0442\u0430'),
        ),
        migrations.AlterField(
            model_name='settingsprivate24',
            name='signature',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='\u041f\u0440\u0438\u0432\u0430\u044224 signature'),
        ),
    ]
