# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-09 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin2', '0010_auto_20170409_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactpagemodel',
            name='name',
            field=models.CharField(default='\u041a\u043e\u043d\u0442\u0430\u043a\u0442\u044b', editable=False, max_length=30, unique=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435'),
        ),
    ]
