# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-09 16:48
from __future__ import unicode_literals

import admin2.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin2', '0011_auto_20170409_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildingpagemodel',
            name='slug',
            field=models.SlugField(allow_unicode=True, default='\u043a\u0432\u0430\u0440\u0442\u0438\u0440\u044b-\u0438-\u0434\u043e\u043c\u0430', editable=False, validators=[admin2.models.slug_validator], verbose_name='URL'),
        ),
        migrations.AddField(
            model_name='contactpagemodel',
            name='slug',
            field=models.SlugField(allow_unicode=True, default='\u043a\u043e\u043d\u0442\u0430\u043a\u0442\u044b', editable=False, validators=[admin2.models.slug_validator], verbose_name='URL'),
        ),
        migrations.AddField(
            model_name='dailypagemodel',
            name='slug',
            field=models.SlugField(allow_unicode=True, default='\u043f\u043e\u0441\u0443\u0442\u043e\u0447\u043d\u0430', editable=False, validators=[admin2.models.slug_validator], verbose_name='URL'),
        ),
        migrations.AddField(
            model_name='indexpagemodel',
            name='slug',
            field=models.SlugField(allow_unicode=True, default='\u0433\u043b\u0430\u0432\u043d\u0430\u044f', editable=False, validators=[admin2.models.slug_validator], verbose_name='URL'),
        ),
        migrations.AddField(
            model_name='newbuildingpagemodel',
            name='slug',
            field=models.SlugField(allow_unicode=True, default='\u043d\u043e\u0432\u043e\u0441\u0442\u0440\u043e\u0438', editable=False, validators=[admin2.models.slug_validator], verbose_name='URL'),
        ),
        migrations.AddField(
            model_name='ofispagemodel',
            name='slug',
            field=models.SlugField(allow_unicode=True, default='\u043e\u0444\u0438\u0441\u044b-\u0438-\u043c\u0430\u0433\u0430\u0437\u0438\u043d\u044b', editable=False, validators=[admin2.models.slug_validator], verbose_name='URL'),
        ),
        migrations.AddField(
            model_name='trustpagemodel',
            name='slug',
            field=models.SlugField(allow_unicode=True, default='\u0434\u043e\u0432\u0435\u0440\u0435\u0435', editable=False, validators=[admin2.models.slug_validator], verbose_name='URL'),
        ),
    ]
