# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-11 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin2', '0011_settingsliqpay'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settingsliqpay',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='settingsprivate24',
            name='currency',
        ),
        migrations.AddField(
            model_name='settingsfranchise',
            name='currency',
            field=models.CharField(blank=True, choices=[('UAH', 'UAH'), ('RUB', 'RUB'), ('USD', 'USD')], max_length=3, verbose_name='\u0412\u0430\u043b\u044e\u0442\u0430'),
        ),
    ]
