# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-11 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin2', '0012_auto_20170511_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settingsliqpay',
            name='merchant',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Liqpay merchant ID'),
        ),
    ]
