# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 02:50
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('admin2', '0012_auto_20170409_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='trustpagemodel',
            name='image',
            field=models.ImageField(blank=True, upload_to='background/%Y/%m/%d/', verbose_name='\u0424\u043e\u0442\u043e'),
        ),
        migrations.AddField(
            model_name='trustpagemodel',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='trustpagemodel',
            name='video',
            field=models.TextField(blank=True, verbose_name='\u041a\u043e\u0434 \u0432\u0438\u0434\u0435\u043e'),
        ),
    ]
