# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-11 22:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin2', '0013_auto_20170511_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexpagemodel',
            name='video',
            field=models.TextField(blank=True, verbose_name='\u041a\u043e\u0434 \u0432\u0438\u0434\u0435\u043e'),
        ),
    ]
