# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-12 01:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin2', '0012_auto_20170512_0440'),
        ('admin2', '0014_indexpagemodel_video'),
    ]

    operations = [
    ]
