# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 10:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin2', '0014_trustpagemodel_faq_enable'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactpagemodel',
            name='image',
            field=models.ImageField(blank=True, upload_to='background/%Y/%m/%d/', verbose_name='\u0424\u043e\u0442\u043e'),
        ),
        migrations.AddField(
            model_name='contactpagemodel',
            name='our_address',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='\u041d\u0430\u0448 \u0430\u0434\u0440\u0435\u0441'),
        ),
        migrations.AddField(
            model_name='contactpagemodel',
            name='our_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='contactpagemodel',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='contact', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contactpagemodel',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
