# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-14 00:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin2', '0016_merge_20170512_1412'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailForward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='\u041f\u043e\u0447\u0442\u0430')),
            ],
        ),
    ]
