# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 15:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin2', '0016_contactpagemodel_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactpagemodel',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='contact', to=settings.AUTH_USER_MODEL, verbose_name='\u041d\u0430\u0448\u0438 \u0441\u043f\u0435\u0446\u0438\u0430\u043b\u0438\u0441\u0442\u044b'),
        ),
    ]
