# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-14 03:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin2', '0017_emailforward'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailforward',
            options={'verbose_name': '\u041f\u043e\u0447\u0442\u0430 \u0434\u043b\u044f \u0440\u0430\u0441\u0441\u044b\u043b\u043a\u0438', 'verbose_name_plural': '\u041f\u043e\u0447\u0442\u0430 \u0434\u043b\u044f \u0440\u0430\u0441\u0441\u044b\u043b\u043a\u0438'},
        ),
    ]
