# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 23:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin2', '0017_auto_20170427_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='name_site',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0441\u0430\u0439\u0442\u0430'),
        ),
    ]
