# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-21 23:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin2', '0035_auto_20170515_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='currency',
            field=models.CharField(blank=True, choices=[('UAH', '\u0433\u0440\u043d'), ('RUB', '\u0440\u0443\u0431'), ('KZT', '\u0442\u043d\u0433'), ('THB', '\u0431\u0430\u0442')], max_length=3, verbose_name='\u0412\u0430\u043b\u044e\u0442\u0430'),
        ),
    ]
