# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin2', '0036_auto_20170522_0205'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter_1', models.TextField(blank=True, null=True, verbose_name='\u0421\u0447\u0435\u0442\u0447\u0438\u043a \u21161')),
                ('counter_2', models.TextField(blank=True, null=True, verbose_name='\u0421\u0447\u0435\u0442\u0447\u0438\u043a \u21162')),
                ('counter_3', models.TextField(blank=True, null=True, verbose_name='\u0421\u0447\u0435\u0442\u0447\u0438\u043a \u21163')),
                ('counter_4', models.TextField(blank=True, null=True, verbose_name='\u0421\u0447\u0435\u0442\u0447\u0438\u043a \u21164')),
            ],
        ),
    ]
