# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-28 14:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin2', '0038_help'),
    ]

    operations = [
        migrations.RenameField(
            model_name='help',
            old_name='vodeo',
            new_name='video',
        ),
    ]
