# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-28 22:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin2', '0040_help_is_enable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='help',
            name='is_enable',
            field=models.BooleanField(default=True, verbose_name='\u0412\u043a\u043b\u044e\u0447\u0435\u043d\u043e?'),
        ),
    ]
