# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-29 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin2', '0041_auto_20170529_0111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settingsaddress',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='\u0422\u0435\u043b\u0435\u0444\u043e\u043d'),
        ),
    ]
