# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-29 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin2', '0042_auto_20170729_1456'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(verbose_name='\u0417\u0430\u0434\u0430\u0447\u0430')),
                ('date_do', models.DateTimeField(blank=True, null=True, verbose_name='\u0414\u043e \u043a\u0430\u043a\u043e\u0433\u043e \u0447\u0438\u0441\u043b\u0430?')),
            ],
            options={
                'ordering': ['date_do'],
                'verbose_name': '\u0417\u0430\u0434\u0430\u0447\u0430',
                'verbose_name_plural': '\u0417\u0430\u0434\u0430\u0447\u0438',
            },
        ),
    ]
