# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 22:54
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rieltor_object', '0002_auto_20170508_0154'),
    ]

    operations = [
        migrations.CreateModel(
            name='Landing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, null=True, unique=True, verbose_name='URL')),
                ('type_deal', models.CharField(choices=[('rent', '\u0410\u0440\u0435\u043d\u0434\u0430'), ('sale', '\u041f\u0440\u043e\u0434\u0430\u0436\u0430'), ('rent_sale', '\u0410\u0440\u0435\u043d\u0434\u0430/\u041f\u0440\u043e\u0434\u0430\u0436\u0430')], max_length=50, verbose_name='\u0410\u0440\u0435\u043d\u0434\u0430 \\ \u043f\u0440\u043e\u0434\u0430\u0436\u0430')),
                ('communication', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('apartment', '\u041a\u0432\u0430\u0440\u0442\u0438\u0440\u0430'), ('house', '\u0414\u043e\u043c'), ('office', '\u041e\u0444\u0438\u0441'), ('shop', '\u041c\u0430\u0433\u0430\u0437\u0438\u043d')], max_length=50, null=True, verbose_name='\u041a\u043e\u043c\u043c\u0443\u043d\u0438\u043a\u0430\u0446\u0438\u0438')),
                ('price_gt', models.IntegerField(blank=True, null=True, verbose_name='\u0426\u0435\u043d\u0430 \u043e\u0442')),
                ('price_lt', models.IntegerField(blank=True, null=True, verbose_name='\u0426\u0435\u043d\u0430 \u0434\u043e')),
                ('footage_gt', models.IntegerField(blank=True, null=True, verbose_name='\u041f\u043b\u043e\u0449\u0430\u0434\u044c \u043e\u0442')),
                ('footage_lt', models.IntegerField(blank=True, null=True, verbose_name='\u041f\u043b\u043e\u0449\u0430\u0434\u044c \u0434\u043e')),
                ('rooms', models.IntegerField(blank=True, null=True, verbose_name='\u041a\u043e\u043c\u043d\u0430\u0442')),
                ('SEOTitle', models.TextField(blank=True, null=True, verbose_name='SEO Title')),
                ('SEOKeywords', models.TextField(blank=True, null=True, verbose_name='SEO Keywords')),
                ('SEODescription', models.TextField(blank=True, null=True, verbose_name='SEO Description')),
                ('title_seo', models.TextField(blank=True, null=True, verbose_name='SEO \u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='\u041a\u043e\u043d\u0442\u0435\u043d\u0442 SEO')),
                ('image_seo', models.ImageField(blank=True, upload_to='landing/%Y/%m/%d/', verbose_name='\u0424\u043e\u0442\u043e SEO')),
                ('image', models.ImageField(blank=True, upload_to='landing/%Y/%m/%d/', verbose_name='\u0424\u043e\u0442\u043e')),
                ('title_footer', models.CharField(blank=True, max_length=200, null=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0434\u043b\u044f \u0444\u0443\u0442\u0435\u0440\u0430')),
                ('title_form', models.CharField(blank=True, max_length=200, null=True, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u0444\u043e\u0440\u043c\u0430')),
                ('subtitle_form', models.CharField(blank=True, max_length=200, null=True, verbose_name='\u041f\u043e\u0434\u0437\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u0444\u043e\u0440\u043c\u0430')),
                ('image_form', models.ImageField(blank=True, upload_to='landing/%Y/%m/%d/', verbose_name='\u0424\u043e\u0442\u043e \u0444\u043e\u0440\u043c\u0430')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='landing', to='rieltor_object.District', verbose_name='\u0420\u0430\u0439\u043e\u043d')),
            ],
            options={
                'verbose_name': '\u041c\u0443\u043b\u044c\u0442\u0438\u043b\u0435\u043d\u0434\u0438\u043d\u0433',
                'verbose_name_plural': '\u041c\u0443\u043b\u044c\u0442\u0438\u043b\u0435\u043d\u0434\u0438\u043d\u0433\u0438',
            },
        ),
    ]
