# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 23:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_landing_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landing',
            name='title',
            field=models.CharField(default=1, max_length=250, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a'),
            preserve_default=False,
        ),
    ]
