# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 23:48
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_auto_20170508_0244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landing',
            name='communication',
        ),
        migrations.AddField(
            model_name='landing',
            name='type_property',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('apartment', '\u041a\u0432\u0430\u0440\u0442\u0438\u0440\u0430'), ('house', '\u0414\u043e\u043c'), ('office', '\u041e\u0444\u0438\u0441'), ('shop', '\u041c\u0430\u0433\u0430\u0437\u0438\u043d')], max_length=50, null=True, verbose_name='\u0422\u0438\u043f \u043d\u0435\u0434\u0432\u0438\u0436\u0438\u043c\u043e\u0441\u0442\u0438'),
        ),
    ]
