# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-08 01:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0004_auto_20170508_0248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landing',
            name='title_seo',
        ),
        migrations.AddField(
            model_name='landing',
            name='title_h1',
            field=models.CharField(default=1, max_length=250, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='landing',
            name='title',
            field=models.TextField(blank=True, null=True, verbose_name='SEO \u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a'),
        ),
    ]
