# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-25 12:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0006_auto_20170525_1539'),
    ]

    operations = [
        migrations.RenameField(
            model_name='landing',
            old_name='title_h1',
            new_name='title',
        ),
    ]
