# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-28 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0007_auto_20170525_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landing',
            name='type_deal',
            field=models.CharField(choices=[('rent', '\u0410\u0440\u0435\u043d\u0434\u0430'), ('sale', '\u041f\u0440\u043e\u0434\u0430\u0436\u0430')], max_length=50, verbose_name='\u0410\u0440\u0435\u043d\u0434\u0430 \\ \u043f\u0440\u043e\u0434\u0430\u0436\u0430'),
        ),
    ]
