# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-29 11:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0008_auto_20170609_1409'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingFutor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('landing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='landing_futor', to='landing.Landing')),
            ],
        ),
    ]
