# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='\u0414\u0430\u0442\u0430 \u0441\u043e\u0437\u0434\u0430\u043d\u0438\u044f')),
                ('source', models.CharField(choices=[('home', '\u0413\u043b\u0430\u0432\u043d\u0430\u044f')], max_length=150, verbose_name='\u0418\u0441\u0442\u043e\u0447\u043d\u0438\u043a')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u0418\u043c\u044f')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u0422\u0435\u043b\u0435\u0444\u043e\u043d')),
                ('email', models.EmailField(blank=True, max_length=200, null=True, verbose_name='Email')),
                ('text', models.TextField(blank=True, null=True, verbose_name='\u041a\u043e\u043c\u043c\u0435\u043d\u0442\u0430\u0440\u0438\u0439')),
            ],
            options={
                'ordering': ['-created'],
                'verbose_name': '\u0417\u0430\u044f\u0432\u043a\u0430',
                'verbose_name_plural': '\u0417\u0430\u044f\u0432\u043a\u0438',
            },
        ),
    ]
