# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 03:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advantage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435')),
                ('image', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='\u0424\u043e\u0442\u043e')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': '\u041f\u0440\u0435\u0438\u043c\u0443\u0449\u0435\u0441\u0442\u0432\u043e',
                'verbose_name_plural': '\u041f\u0440\u0435\u0438\u043c\u0443\u0449\u0435\u0441\u0442\u0432\u0430',
            },
        ),
        migrations.CreateModel(
            name='ApartmentNext',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('value', models.IntegerField(verbose_name='\u0417\u043d\u0430\u0447\u0435\u043d\u0438\u0435')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'ordering': ['-id'],
                'verbose_name': '\u0420\u044f\u0434\u043e\u043c \u0441 \u043a\u0432\u0430\u0440\u0442\u0438\u0440\u043e\u0439',
                'verbose_name_plural': '\u0420\u044f\u0434\u043e\u043c \u0441 \u043a\u0432\u0430\u0440\u0442\u0438\u0440\u043e\u0439',
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='\u0414\u0430\u0442\u0430 \u0441\u043e\u0437\u0434\u0430\u043d\u0438\u044f')),
                ('source', models.CharField(choices=[('home', '\u0413\u043b\u0430\u0432\u043d\u0430\u044f')], max_length=150, verbose_name='\u0418\u0441\u0442\u043e\u0447\u043d\u0438\u043a')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u0418\u043c\u044f')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u0422\u0435\u043b\u0435\u0444\u043e\u043d')),
                ('email', models.EmailField(blank=True, max_length=200, null=True, verbose_name='Email')),
                ('text', models.TextField(blank=True, null=True, verbose_name='\u041a\u043e\u043c\u043c\u0435\u043d\u0442\u0430\u0440\u0438\u0439')),
            ],
            options={
                'ordering': ['-created'],
                'verbose_name': '\u0417\u0430\u044f\u0432\u043a\u0430',
                'verbose_name_plural': '\u0417\u0430\u044f\u0432\u043a\u0438',
            },
        ),
        migrations.CreateModel(
            name='BasePacket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='\u041d\u0430\u0447\u0438\u043d\u0430\u044e\u0449\u0438\u0439', max_length=250, verbose_name='\u041d\u0430\u0447\u0438\u043d\u0430\u044e\u0449\u0438\u0439')),
            ],
            options={
                'verbose_name': '\u041f\u0430\u043a\u0435\u0442 \u041d\u0430\u0447\u0438\u043d\u0430\u044e\u0449\u0438\u0439',
                'verbose_name_plural': '\u041f\u0430\u043a\u0435\u0442 \u041d\u0430\u0447\u0438\u043d\u0430\u044e\u0449\u0438\u0439',
            },
        ),
        migrations.CreateModel(
            name='ExpertPacket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='\u042d\u043a\u0441\u043f\u0435\u0440\u0442', max_length=250, verbose_name='\u042d\u043a\u0441\u043f\u0435\u0440\u0442')),
            ],
            options={
                'verbose_name': '\u041f\u0430\u043a\u0435\u0442 \u042d\u043a\u0441\u043f\u0435\u0440\u0442',
                'verbose_name_plural': '\u041f\u0430\u043a\u0435\u0442 \u042d\u043a\u0441\u043f\u0435\u0440\u0442',
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, null=True, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a')),
                ('text', models.TextField(blank=True, verbose_name='\u0422\u0435\u043a\u0441\u0442')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': '\u0427\u0410\u0421\u0422\u041e \u0417\u0410\u0414\u0410\u0412\u0410\u0415\u041c\u042b\u0415 \u0412\u041e\u041f\u0420\u041e\u0421\u042b',
                'verbose_name_plural': '\u0427\u0410\u0421\u0422\u041e \u0417\u0410\u0414\u0410\u0412\u0410\u0415\u041c\u042b\u0415 \u0412\u041e\u041f\u0420\u041e\u0421\u042b',
            },
        ),
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True, verbose_name='\u0418\u043c\u044f')),
                ('city', models.CharField(blank=True, max_length=250, null=True, verbose_name='\u0413\u043e\u0440\u043e\u0434')),
                ('feed', models.TextField(blank=True, null=True, verbose_name='\u041e\u0442\u0437\u0438\u0432')),
                ('image', models.ImageField(blank=True, upload_to='feed/%Y/%m/%d/', verbose_name='\u0424\u043e\u0442\u043e')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': '\u041e\u0442\u0437\u0438\u0432',
                'verbose_name_plural': '\u041e\u0442\u0437\u0438\u0432\u044b',
            },
        ),
        migrations.CreateModel(
            name='Finish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a')),
                ('description', models.TextField(verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='\u041a\u043e\u043c\u043c\u0435\u043d\u0442\u0430\u0440\u0438\u0439')),
                ('priority', models.CharField(blank=True, choices=[('\u0421\u043b\u043e\u0436\u043d\u043e\u0435', '\u0421\u043b\u043e\u0436\u043d\u043e\u0435'), ('\u041f\u0440\u043e\u0441\u0442\u043e\u0435', '\u041f\u0440\u043e\u0441\u0442\u043e\u0435'), ('\u0421\u0440\u0435\u0434\u043d\u0435\u0435', '\u0421\u0440\u0435\u0434\u043d\u0435\u0435')], max_length=20, null=True, verbose_name='\u041f\u0440\u0438\u043e\u0440\u0438\u0442\u0435\u0442 \u0437\u0430\u0434\u0430\u043d\u0438\u044f')),
                ('when_do', models.DateField(blank=True, null=True, verbose_name='\u041a\u043e\u0433\u0434\u0430 \u043f\u0440\u0438\u0441\u0442\u0443\u043f\u0438\u0442\u0435?')),
                ('plan_do', models.DateField(blank=True, null=True, verbose_name='\u041f\u043b\u0430\u043d\u0438\u0440\u0443\u0435\u0442\u0435 \u0432\u044b\u043f\u043e\u043b\u043d\u0438\u0442\u044c')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': '\u0417\u0430\u0432\u0435\u0440\u0448\u0435\u043d\u0438\u0435',
                'verbose_name_plural': '\u0417\u0430\u0432\u0435\u0440\u0448\u0435\u043d\u0438\u0435',
            },
        ),
        migrations.CreateModel(
            name='MidlePacket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='\u041f\u0440\u043e\u0434\u0432\u0438\u043d\u0443\u0442\u044b\u0439', max_length=250, verbose_name='\u041f\u0440\u043e\u0434\u0432\u0438\u043d\u0443\u0442\u044b\u0439')),
            ],
            options={
                'verbose_name': '\u041f\u0430\u043a\u0435\u0442 \u041f\u0440\u043e\u0434\u0432\u0438\u043d\u0443\u0442\u044b\u0439',
                'verbose_name_plural': '\u041f\u0430\u043a\u0435\u0442 \u041f\u0440\u043e\u0434\u0432\u0438\u043d\u0443\u0442\u044b\u0439',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, null=True, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a')),
                ('image', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='\u0424\u043e\u0442\u043e')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': '\u0424\u043e\u0442\u043e',
                'verbose_name_plural': '\u0424\u043e\u0442\u043e',
            },
        ),
        migrations.CreateModel(
            name='Preparation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a')),
                ('description', models.TextField(verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='\u041a\u043e\u043c\u043c\u0435\u043d\u0442\u0430\u0440\u0438\u0439')),
                ('priority', models.CharField(blank=True, choices=[('\u0421\u043b\u043e\u0436\u043d\u043e\u0435', '\u0421\u043b\u043e\u0436\u043d\u043e\u0435'), ('\u041f\u0440\u043e\u0441\u0442\u043e\u0435', '\u041f\u0440\u043e\u0441\u0442\u043e\u0435'), ('\u0421\u0440\u0435\u0434\u043d\u0435\u0435', '\u0421\u0440\u0435\u0434\u043d\u0435\u0435')], max_length=20, null=True, verbose_name='\u041f\u0440\u0438\u043e\u0440\u0438\u0442\u0435\u0442 \u0437\u0430\u0434\u0430\u043d\u0438\u044f')),
                ('when_do', models.DateField(blank=True, null=True, verbose_name='\u041a\u043e\u0433\u0434\u0430 \u043f\u0440\u0438\u0441\u0442\u0443\u043f\u0438\u0442\u0435?')),
                ('plan_do', models.DateField(blank=True, null=True, verbose_name='\u041f\u043b\u0430\u043d\u0438\u0440\u0443\u0435\u0442\u0435 \u0432\u044b\u043f\u043e\u043b\u043d\u0438\u0442\u044c')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': '\u041f\u043e\u0434\u0433\u043e\u0442\u043e\u0432\u043a\u0430',
                'verbose_name_plural': '\u041f\u043e\u0434\u0433\u043e\u0442\u043e\u0432\u043a\u0438',
            },
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a')),
                ('description', models.TextField(verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='\u041a\u043e\u043c\u043c\u0435\u043d\u0442\u0430\u0440\u0438\u0439')),
                ('priority', models.CharField(blank=True, choices=[('\u0421\u043b\u043e\u0436\u043d\u043e\u0435', '\u0421\u043b\u043e\u0436\u043d\u043e\u0435'), ('\u041f\u0440\u043e\u0441\u0442\u043e\u0435', '\u041f\u0440\u043e\u0441\u0442\u043e\u0435'), ('\u0421\u0440\u0435\u0434\u043d\u0435\u0435', '\u0421\u0440\u0435\u0434\u043d\u0435\u0435')], max_length=20, null=True, verbose_name='\u041f\u0440\u0438\u043e\u0440\u0438\u0442\u0435\u0442 \u0437\u0430\u0434\u0430\u043d\u0438\u044f')),
                ('when_do', models.DateField(blank=True, null=True, verbose_name='\u041a\u043e\u0433\u0434\u0430 \u043f\u0440\u0438\u0441\u0442\u0443\u043f\u0438\u0442\u0435?')),
                ('plan_do', models.DateField(blank=True, null=True, verbose_name='\u041f\u043b\u0430\u043d\u0438\u0440\u0443\u0435\u0442\u0435 \u0432\u044b\u043f\u043e\u043b\u043d\u0438\u0442\u044c')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': '\u041f\u0440\u043e\u0446\u0435\u0441\u0441',
                'verbose_name_plural': '\u041f\u0440\u043e\u0446\u0435\u0441\u0441',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(blank=True, choices=[('\u041f\u043e\u043d\u0435\u0434\u0435\u043b\u044c\u043d\u0438\u043a', '\u041f\u043e\u043d\u0435\u0434\u0435\u043b\u044c\u043d\u0438\u043a'), ('\u0412\u0442\u043e\u0440\u043d\u0438\u043a', '\u0412\u0442\u043e\u0440\u043d\u0438\u043a'), ('\u0421\u0440\u0435\u0434\u0430', '\u0421\u0440\u0435\u0434\u0430'), ('\u0427\u0435\u0442\u0432\u0435\u0440\u0433', '\u0427\u0435\u0442\u0432\u0435\u0440\u0433'), ('\u041f\u044f\u0442\u043d\u0438\u0446\u0430', '\u041f\u044f\u0442\u043d\u0438\u0446\u0430'), ('\u0421\u0443\u0431\u0431\u043e\u0442\u0430', '\u0421\u0443\u0431\u0431\u043e\u0442\u0430'), ('\u0412\u043e\u0441\u043a\u0440\u0435\u0441\u0435\u043d\u044c\u0435', '\u0412\u043e\u0441\u043a\u0440\u0435\u0441\u0435\u043d\u044c\u0435')], max_length=25, null=True, verbose_name='\u0414\u0435\u043d\u044c \u043d\u0435\u0434\u0435\u043b\u0438')),
                ('open_from', models.TimeField(blank=True, null=True, verbose_name='\u0427\u0430\u0441\u043e\u0432 \u041e\u0442')),
                ('open_to', models.TimeField(blank=True, null=True, verbose_name='\u0427\u0430\u0441\u043e\u0432 \u0414\u043e')),
                ('special', models.CharField(blank=True, help_text='\u0414\u0440\u0443\u0433\u043e\u0435 \u0431\u0443\u0434\u0435\u0442 \u0438\u0433\u043d\u043e\u0440\u0438\u0440\u043e\u0432\u0430\u0442\u0441\u044f', max_length=250, null=True, verbose_name='C\u043e\u0431\u0441\u0442\u0432\u0435\u043d\u043d\u043e\u0435 \u0437\u043d\u0430\u0447\u0435\u043d\u0438\u0435')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': '\u0413\u0440\u0430\u0444\u0438\u043a \u0440\u0430\u0431\u043e\u0442\u044b',
                'verbose_name_plural': '\u0413\u0440\u0430\u0444\u0438\u043a \u0440\u0430\u0431\u043e\u0442\u044b',
            },
        ),
        migrations.CreateModel(
            name='TableRepair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True, verbose_name='\u041d\u0430\u0438\u043c\u0435\u043d\u043e\u0432\u0430\u043d\u0438\u0435 \u0440\u0430\u0431\u043e\u0442')),
                ('price', models.CharField(blank=True, max_length=250, null=True, verbose_name='\u0421\u0442\u043e\u0438\u043c\u043e\u0441\u0442\u044c')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': '\u0421\u0442\u043e\u0438\u043c\u043e\u0441\u0442\u044c \u0440\u0435\u043c\u043e\u043d\u0442\u0430',
                'verbose_name_plural': '\u0421\u0442\u043e\u0438\u043c\u043e\u0441\u0442\u044c \u0440\u0435\u043c\u043e\u043d\u0442\u0430',
            },
        ),
        migrations.CreateModel(
            name='TextPacket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='\u0422\u0435\u043a\u0441\u0442')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': '\u0422\u0435\u043a\u0441\u0442 \u043f\u0430\u043a\u0435\u0442\u0430',
                'verbose_name_plural': '\u0422\u0435\u043a\u0441\u0442 \u043f\u0430\u043a\u0435\u0442\u043e\u0432',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, null=True, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a')),
                ('video', models.TextField(blank=True, verbose_name='\u041a\u043e\u0434 \u0432\u0438\u0434\u0435\u043e')),
                ('is_enable', models.BooleanField(default=True, verbose_name='\u0412\u043a\u043b\u044e\u0447\u0435\u043d \u043b\u0438?')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': '\u0412\u0438\u0434\u0435\u043e',
                'verbose_name_plural': '\u0412\u0438\u0434\u0435\u043e',
            },
        ),
        migrations.CreateModel(
            name='WhatYouKnown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True, verbose_name='\u0422\u0435\u043a\u0441\u0442')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': '\u0427\u0442\u043e \u0432\u044b \u0443\u0437\u043d\u0430\u0435\u0442\u0435',
                'verbose_name_plural': '\u0427\u0442\u043e \u0432\u044b \u0443\u0437\u043d\u0430\u0435\u0442\u0435',
            },
        ),
    ]
