# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-12 01:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_application_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='price',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='\u0426\u0435\u043d\u0430'),
        ),
    ]
