# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 17:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20170307_2040'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['-created'], 'verbose_name': '\u0417\u0430\u044f\u0432\u043a\u0430', 'verbose_name_plural': '\u0417\u0430\u044f\u0432\u043a\u0438'},
        ),
    ]
