# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-12 01:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_application_price'),
        ('common', '0002_auto_20170512_0440'),
    ]

    operations = [
    ]
