# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-06 15:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('common', '0005_tablerepair'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasePacket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='\u041d\u0430\u0447\u0438\u043d\u0430\u044e\u0449\u0438\u0439', max_length=250, verbose_name='\u041d\u0430\u0447\u0438\u043d\u0430\u044e\u0449\u0438\u0439')),
            ],
            options={
                'verbose_name': '\u041f\u0430\u043a\u0435\u0442 \u041d\u0430\u0447\u0438\u043d\u0430\u044e\u0449\u0438\u0439',
                'verbose_name_plural': '\u041f\u0430\u043a\u0435\u0442 \u041d\u0430\u0447\u0438\u043d\u0430\u044e\u0449\u0438\u0439',
            },
        ),
        migrations.CreateModel(
            name='TextPacket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='\u0422\u0435\u043a\u0441\u0442')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': '\u0422\u0435\u043a\u0441\u0442 \u043f\u0430\u043a\u0435\u0442\u0430',
                'verbose_name_plural': '\u0422\u0435\u043a\u0441\u0442 \u043f\u0430\u043a\u0435\u0442\u043e\u0432',
            },
        ),
    ]
