# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-06 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_basepacket_textpacket'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpertPacket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='\u042d\u043a\u0441\u043f\u0435\u0440\u0442', max_length=250, verbose_name='\u042d\u043a\u0441\u043f\u0435\u0440\u0442')),
            ],
            options={
                'verbose_name': '\u041f\u0430\u043a\u0435\u0442 \u042d\u043a\u0441\u043f\u0435\u0440\u0442',
                'verbose_name_plural': '\u041f\u0430\u043a\u0435\u0442 \u042d\u043a\u0441\u043f\u0435\u0440\u0442',
            },
        ),
        migrations.CreateModel(
            name='MidlePacket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='\u041f\u0440\u043e\u0434\u0432\u0438\u043d\u0443\u0442\u044b\u0439', max_length=250, verbose_name='\u041f\u0440\u043e\u0434\u0432\u0438\u043d\u0443\u0442\u044b\u0439')),
            ],
            options={
                'verbose_name': '\u041f\u0430\u043a\u0435\u0442 \u041f\u0440\u043e\u0434\u0432\u0438\u043d\u0443\u0442\u044b\u0439',
                'verbose_name_plural': '\u041f\u0430\u043a\u0435\u0442 \u041f\u0440\u043e\u0434\u0432\u0438\u043d\u0443\u0442\u044b\u0439',
            },
        ),
    ]
