# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-13 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_auto_20170512_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='comming',
            field=models.TextField(blank=True, null=True, verbose_name='\u0417\u0430\u0435\u0437\u0434'),
        ),
        migrations.AddField(
            model_name='application',
            name='go',
            field=models.TextField(blank=True, null=True, verbose_name='\u041e\u0442\u044c\u0435\u0437\u0434'),
        ),
    ]
