# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_advantage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='is_enable',
            field=models.BooleanField(default=True, verbose_name='\u0412\u043a\u043b\u044e\u0447\u0435\u043d \u043b\u0438?'),
        ),
    ]
