# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 13:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('common', '0009_auto_20170418_1901'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApartmentNext',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('value', models.IntegerField(verbose_name='\u0417\u043d\u0430\u0447\u0435\u043d\u0438\u0435')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': '\u0420\u044f\u0434\u043e\u043c \u0441 \u043a\u0432\u0430\u0440\u0442\u0438\u0440\u043e\u0439',
                'verbose_name_plural': '\u0420\u044f\u0434\u043e\u043c \u0441 \u043a\u0432\u0430\u0440\u0442\u0438\u0440\u043e\u0439',
            },
        ),
    ]
