# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 02:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('common', '0011_auto_20170424_2030'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True, verbose_name='\u0418\u043c\u044f')),
                ('city', models.CharField(blank=True, max_length=250, null=True, verbose_name='\u0413\u043e\u0440\u043e\u0434')),
                ('feed', models.TextField(blank=True, null=True, verbose_name='\u041e\u0442\u0437\u0438\u0432')),
                ('image', models.ImageField(blank=True, upload_to='feed/%Y/%m/%d/', verbose_name='\u0424\u043e\u0442\u043e')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': '\u041e\u0442\u0437\u0438\u0432',
                'verbose_name_plural': '\u041e\u0442\u0437\u0438\u0432\u044b',
            },
        ),
    ]
