# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-25 02:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('common', '0012_auto_20170517_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='application',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
