# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 15:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('common', '0013_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatYouKnown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True, verbose_name='\u0422\u0435\u043a\u0441\u0442')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': '\u0427\u0442\u043e \u0432\u044b \u0443\u0437\u043d\u0430\u0435\u0442\u0435',
                'verbose_name_plural': '\u0427\u0442\u043e \u0432\u044b \u0443\u0437\u043d\u0430\u0435\u0442\u0435',
            },
        ),
    ]
