# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 19:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('common', '0015_preparation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Finish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': '\u0417\u0430\u0432\u0435\u0440\u0448\u0435\u043d\u0438\u0435',
                'verbose_name_plural': '\u0417\u0430\u0432\u0435\u0440\u0448\u0435\u043d\u0438\u0435',
            },
        ),
        migrations.CreateModel(
            name='PlanType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a')),
                ('description', models.TextField(verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435')),
                ('priority', models.CharField(blank=True, choices=[('\u0421\u043b\u043e\u0436\u043d\u043e\u0435', '\u0421\u043b\u043e\u0436\u043d\u043e\u0435'), ('\u041f\u0440\u043e\u0441\u0442\u043e\u0435', '\u041f\u0440\u043e\u0441\u0442\u043e\u0435'), ('\u0421\u0440\u0435\u0434\u043d\u0435\u0435', '\u0421\u0440\u0435\u0434\u043d\u0435\u0435')], max_length=20, null=True, verbose_name='\u041f\u0440\u0438\u043e\u0440\u0438\u0442\u0435\u0442 \u0437\u0430\u0434\u0430\u043d\u0438\u044f')),
                ('when_do', models.DateField(blank=True, null=True, verbose_name='\u041a\u043e\u0433\u0434\u0430 \u043f\u0440\u0438\u0441\u0442\u0443\u043f\u0438\u0442\u0435?')),
                ('plan_do', models.DateField(blank=True, null=True, verbose_name='\u041f\u043b\u0430\u043d\u0438\u0440\u0443\u0435\u0442\u0435 \u0432\u044b\u043f\u043e\u043b\u043d\u0438\u0442\u044c')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': '\u041f\u043e\u0434\u0433\u043e\u0442\u043e\u0432\u043a\u0430',
                'verbose_name_plural': '\u041f\u043e\u0434\u0433\u043e\u0442\u043e\u0432\u043a\u0438',
            },
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': '\u041f\u0440\u043e\u0446\u0435\u0441\u0441',
                'verbose_name_plural': '\u041f\u0440\u043e\u0446\u0435\u0441\u0441',
            },
        ),
        migrations.AlterModelOptions(
            name='preparation',
            options={'verbose_name': '\u041f\u043e\u0434\u0433\u043e\u0442\u043e\u0432\u043a\u0430', 'verbose_name_plural': '\u041f\u043e\u0434\u0433\u043e\u0442\u043e\u0432\u043a\u0438'},
        ),
        migrations.AddField(
            model_name='preparation',
            name='content_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='preparation',
            name='object_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
