# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 19:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0016_auto_20170428_2230'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plantype',
            options={'verbose_name': '\u0422\u0438\u043f\u0438 \u041f\u043b\u0430\u043d\u043e\u0432', 'verbose_name_plural': '\u0422\u0438\u043f\u0438 \u041f\u043b\u0430\u043d\u043e\u0432'},
        ),
    ]
