# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0017_auto_20170428_2235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantype',
            name='content_type',
        ),
        migrations.AddField(
            model_name='finish',
            name='description',
            field=models.TextField(default=1, verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='finish',
            name='plan_do',
            field=models.DateField(blank=True, null=True, verbose_name='\u041f\u043b\u0430\u043d\u0438\u0440\u0443\u0435\u0442\u0435 \u0432\u044b\u043f\u043e\u043b\u043d\u0438\u0442\u044c'),
        ),
        migrations.AddField(
            model_name='finish',
            name='priority',
            field=models.CharField(blank=True, choices=[('\u0421\u043b\u043e\u0436\u043d\u043e\u0435', '\u0421\u043b\u043e\u0436\u043d\u043e\u0435'), ('\u041f\u0440\u043e\u0441\u0442\u043e\u0435', '\u041f\u0440\u043e\u0441\u0442\u043e\u0435'), ('\u0421\u0440\u0435\u0434\u043d\u0435\u0435', '\u0421\u0440\u0435\u0434\u043d\u0435\u0435')], max_length=20, null=True, verbose_name='\u041f\u0440\u0438\u043e\u0440\u0438\u0442\u0435\u0442 \u0437\u0430\u0434\u0430\u043d\u0438\u044f'),
        ),
        migrations.AddField(
            model_name='finish',
            name='title',
            field=models.TextField(default=1, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='finish',
            name='when_do',
            field=models.DateField(blank=True, null=True, verbose_name='\u041a\u043e\u0433\u0434\u0430 \u043f\u0440\u0438\u0441\u0442\u0443\u043f\u0438\u0442\u0435?'),
        ),
        migrations.AddField(
            model_name='preparation',
            name='description',
            field=models.TextField(default=1, verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='preparation',
            name='plan_do',
            field=models.DateField(blank=True, null=True, verbose_name='\u041f\u043b\u0430\u043d\u0438\u0440\u0443\u0435\u0442\u0435 \u0432\u044b\u043f\u043e\u043b\u043d\u0438\u0442\u044c'),
        ),
        migrations.AddField(
            model_name='preparation',
            name='priority',
            field=models.CharField(blank=True, choices=[('\u0421\u043b\u043e\u0436\u043d\u043e\u0435', '\u0421\u043b\u043e\u0436\u043d\u043e\u0435'), ('\u041f\u0440\u043e\u0441\u0442\u043e\u0435', '\u041f\u0440\u043e\u0441\u0442\u043e\u0435'), ('\u0421\u0440\u0435\u0434\u043d\u0435\u0435', '\u0421\u0440\u0435\u0434\u043d\u0435\u0435')], max_length=20, null=True, verbose_name='\u041f\u0440\u0438\u043e\u0440\u0438\u0442\u0435\u0442 \u0437\u0430\u0434\u0430\u043d\u0438\u044f'),
        ),
        migrations.AddField(
            model_name='preparation',
            name='title',
            field=models.TextField(default=1, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='preparation',
            name='when_do',
            field=models.DateField(blank=True, null=True, verbose_name='\u041a\u043e\u0433\u0434\u0430 \u043f\u0440\u0438\u0441\u0442\u0443\u043f\u0438\u0442\u0435?'),
        ),
        migrations.AddField(
            model_name='process',
            name='description',
            field=models.TextField(default=1, verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='process',
            name='plan_do',
            field=models.DateField(blank=True, null=True, verbose_name='\u041f\u043b\u0430\u043d\u0438\u0440\u0443\u0435\u0442\u0435 \u0432\u044b\u043f\u043e\u043b\u043d\u0438\u0442\u044c'),
        ),
        migrations.AddField(
            model_name='process',
            name='priority',
            field=models.CharField(blank=True, choices=[('\u0421\u043b\u043e\u0436\u043d\u043e\u0435', '\u0421\u043b\u043e\u0436\u043d\u043e\u0435'), ('\u041f\u0440\u043e\u0441\u0442\u043e\u0435', '\u041f\u0440\u043e\u0441\u0442\u043e\u0435'), ('\u0421\u0440\u0435\u0434\u043d\u0435\u0435', '\u0421\u0440\u0435\u0434\u043d\u0435\u0435')], max_length=20, null=True, verbose_name='\u041f\u0440\u0438\u043e\u0440\u0438\u0442\u0435\u0442 \u0437\u0430\u0434\u0430\u043d\u0438\u044f'),
        ),
        migrations.AddField(
            model_name='process',
            name='title',
            field=models.TextField(default=1, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='process',
            name='when_do',
            field=models.DateField(blank=True, null=True, verbose_name='\u041a\u043e\u0433\u0434\u0430 \u043f\u0440\u0438\u0441\u0442\u0443\u043f\u0438\u0442\u0435?'),
        ),
        migrations.DeleteModel(
            name='PlanType',
        ),
    ]
