# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0018_auto_20170428_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='finish',
            name='comment',
            field=models.TextField(default=1, verbose_name='\u041a\u043e\u043c\u043c\u0435\u043d\u0442\u0430\u0440\u0438\u0439'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='preparation',
            name='comment',
            field=models.TextField(default=1, verbose_name='\u041a\u043e\u043c\u043c\u0435\u043d\u0442\u0430\u0440\u0438\u0439'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='process',
            name='comment',
            field=models.TextField(default=1, verbose_name='\u041a\u043e\u043c\u043c\u0435\u043d\u0442\u0430\u0440\u0438\u0439'),
            preserve_default=False,
        ),
    ]
