# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 03:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accommodations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='icons/%Y/%m/%d/', verbose_name='\u0424\u043e\u0442\u043e')),
                ('title', models.CharField(max_length=250, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a')),
                ('description', models.CharField(max_length=250, verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435')),
            ],
            options={
                'verbose_name': '\u0423\u0441\u043b\u043e\u0432\u0438\u044f \u043f\u0440\u043e\u0436\u0438\u0432\u0430\u043d\u0438\u044f',
                'verbose_name_plural': '\u0423\u0441\u043b\u043e\u0432\u0438\u044f \u043f\u0440\u043e\u0436\u0438\u0432\u0430\u043d\u0438\u044f',
            },
        ),
        migrations.CreateModel(
            name='ApartmentHas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
            ],
            options={
                'verbose_name': '\u0412 \u043a\u0432\u0430\u0440\u0442\u0438\u0440\u0435 \u0435\u0441\u0442\u044c',
                'verbose_name_plural': '\u0412 \u043a\u0432\u0430\u0440\u0442\u0438\u0440\u0435 \u0435\u0441\u0442\u044c',
            },
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, null=True, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a')),
                ('SEOTitle', models.TextField(blank=True, null=True, verbose_name='SEO Title')),
                ('SEOKeywords', models.TextField(blank=True, null=True, verbose_name='SEO Keywords')),
                ('SEODescription', models.TextField(blank=True, null=True, verbose_name='SEO Description')),
                ('address', models.CharField(blank=True, max_length=250, null=True, verbose_name='\u0410\u0434\u0440\u0435\u0441')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='\u0426\u0435\u043d\u0430')),
                ('type_deal', models.CharField(blank=True, choices=[('rent', '\u0410\u0440\u0435\u043d\u0434\u0430'), ('sale', '\u041f\u0440\u043e\u0434\u0430\u0436\u0430')], max_length=20, null=True, verbose_name='\u0422\u0438\u043f')),
                ('appointment', models.CharField(blank=True, choices=[('apartment', '\u041a\u0432\u0430\u0440\u0442\u0438\u0440\u0430'), ('house', '\u0414\u043e\u043c')], max_length=20, null=True, verbose_name='\u041d\u0430\u0437\u043d\u0430\u0447\u0435\u043d\u0438\u0435')),
                ('footage', models.IntegerField(blank=True, null=True, verbose_name='\u041f\u043b\u043e\u0449\u0430\u0434\u044c')),
                ('rooms', models.IntegerField(blank=True, null=True, verbose_name='\u041a\u043e\u043c\u043d\u0430\u0442')),
                ('point', models.IntegerField(blank=True, null=True, verbose_name='\u0411\u0430\u043b\u044b')),
                ('when_create', models.DateTimeField(auto_now_add=True, verbose_name='\u0414\u0430\u0442\u0430 \u043f\u0443\u0431\u043b\u0438\u043a\u0430\u0446\u0438\u0438')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='\u0414\u0430\u0442\u0430 \u0440\u0435\u0434\u0430\u043a\u0442\u0438\u0440\u043e\u0432\u0430\u043d\u0438\u044f')),
                ('location', models.CharField(blank=True, choices=[('facade', '\u0424\u0430\u0441\u0430\u0434'), ('from_yard', '\u0414\u0432\u043e\u0440\u043e\u0432\u043e\u0439'), ('business_center', '\u0411\u0438\u0437\u043d\u0435\u0441-\u0446\u0435\u043d\u0442\u0440')], max_length=20, null=True, verbose_name='\u0420\u0430\u0441\u043f\u043e\u043b\u043e\u0436\u0435\u043d\u0438\u0435')),
                ('floor', models.CharField(blank=True, choices=[('first', '1-\u0439'), ('base', '\u0426\u043e\u043a\u043e\u043b\u044c'), ('mezzanine', '\u0411\u0435\u043b\u044c\u044d\u0442\u0430\u0436')], max_length=20, null=True, verbose_name='\u042d\u0442\u0430\u0436')),
                ('entrance', models.CharField(blank=True, choices=[('facade', '\u0424\u0430\u0441\u0430\u0434'), ('from_yard', '\u0421\u043e \u0434\u0432\u043e\u0440\u0430'), ('with_grand', '\u0421 \u043f\u0430\u0440\u0430\u0434\u043d\u043e\u0439')], max_length=20, null=True, verbose_name='\u0412\u0445\u043e\u0434')),
                ('status', models.CharField(blank=True, choices=[('vip', 'VIP'), ('default', '\u041e\u0431\u044b\u0447\u043d\u043e\u0435'), ('short', '\u041a\u0440\u0430\u0442\u043a\u043e\u0435')], max_length=20, null=True, verbose_name='\u0421\u0442\u0430\u0442\u0443\u0441')),
                ('description', models.TextField(blank=True, verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435')),
                ('panorama', models.TextField(blank=True, verbose_name='\u041f\u0430\u043d\u043e\u0440\u0430\u043c\u0430')),
                ('geo', models.TextField(blank=True, verbose_name='\u041d\u0430 \u043a\u0430\u0440\u0442\u0435')),
                ('views', models.IntegerField(default=0, verbose_name='\u041f\u0440\u043e\u0441\u043c\u043e\u0442\u0440\u044b')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
            ],
            options={
                'ordering': ['-when_create'],
                'verbose_name': '\u041a\u0432\u0430\u0440\u0442\u0438\u0440\u044b \u0438 \u0414\u043e\u043c\u0430',
                'verbose_name_plural': '\u041a\u0432\u0430\u0440\u0442\u0438\u0440\u044b \u0438 \u0414\u043e\u043c\u0430',
            },
        ),
        migrations.CreateModel(
            name='Daily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, null=True, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a')),
                ('SEOTitle', models.TextField(blank=True, null=True, verbose_name='SEO Title')),
                ('SEOKeywords', models.TextField(blank=True, null=True, verbose_name='SEO Keywords')),
                ('SEODescription', models.TextField(blank=True, null=True, verbose_name='SEO Description')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='\u0426\u0435\u043d\u0430')),
                ('address', models.CharField(blank=True, max_length=250, null=True, verbose_name='\u0410\u0434\u0440\u0435\u0441')),
                ('floor', models.IntegerField(blank=True, null=True, verbose_name='\u042d\u0442\u0430\u0436')),
                ('guest', models.IntegerField(blank=True, null=True, verbose_name='\u0413\u043e\u0441\u0442\u0435\u0439')),
                ('sleeping_places', models.IntegerField(blank=True, null=True, verbose_name='\u0421\u043f\u0430\u043b\u044c\u043d\u044b\u0445 \u043c\u0435\u0441\u0442')),
                ('rooms', models.IntegerField(blank=True, null=True, verbose_name='\u041a\u043e\u043c\u043d\u0430\u0442')),
                ('description', models.TextField(blank=True, verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435')),
                ('panorama', models.TextField(blank=True, verbose_name='\u041f\u0430\u043d\u043e\u0440\u0430\u043c\u0430')),
                ('geo', models.TextField(blank=True, verbose_name='\u041d\u0430 \u043a\u0430\u0440\u0442\u0435')),
                ('views', models.IntegerField(default=0, verbose_name='\u041f\u0440\u043e\u0441\u043c\u043e\u0442\u0440\u044b')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('when_create', models.DateTimeField(auto_now_add=True, verbose_name='\u0414\u0430\u0442\u0430 \u043f\u0443\u0431\u043b\u0438\u043a\u0430\u0446\u0438\u0438')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='\u0414\u0430\u0442\u0430 \u0440\u0435\u0434\u0430\u043a\u0442\u0438\u0440\u043e\u0432\u0430\u043d\u0438\u044f')),
                ('image', models.ImageField(blank=True, upload_to='background/%Y/%m/%d/', verbose_name='\u0424\u043e\u0442\u043e')),
                ('point', models.IntegerField(blank=True, null=True, verbose_name='\u0411\u0430\u043b\u044b')),
                ('apartment_has', models.ManyToManyField(blank=True, help_text='\u0414\u043b\u044f \u0441\u043e\u0437\u0434\u0430\u043d\u0438\u044f \u0437\u043d\u0430\u0447\u0435\u043d\u0438\u044f \u043d\u0430\u0447\u043d\u0438\u0442\u0435 \u043d\u0430\u0431\u0438\u0440\u0430\u0442\u044c \u0442\u0435\u043a\u0441\u0442', related_name='daily', to='rieltor_object.ApartmentHas', verbose_name='\u0412 \u043a\u0432\u0430\u0440\u0442\u0438\u0440\u0435 \u0435\u0441\u0442\u044c')),
            ],
            options={
                'ordering': ['-when_create'],
                'verbose_name': '\u041f\u043e\u0441\u0443\u0442\u043e\u0447\u043d\u043e',
                'verbose_name_plural': '\u041f\u043e\u0441\u0443\u0442\u043e\u0447\u043d\u043e',
            },
        ),
        migrations.CreateModel(
            name='DailyDistrict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
            ],
            options={
                'verbose_name': '\u0420\u0430\u0439\u043e\u043d \u0434\u043b\u044f \u043f\u043e\u0441\u0443\u0442\u043e\u0447\u043d\u043e',
                'verbose_name_plural': '\u0420\u0430\u0439\u043e\u043d\u044b \u0434\u043b\u044f \u043f\u043e\u0441\u0443\u0442\u043e\u0447\u043d\u043e',
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
            ],
            options={
                'verbose_name': '\u0420\u0430\u0439\u043e\u043d',
                'verbose_name_plural': '\u0420\u0430\u0439\u043e\u043d\u044b',
            },
        ),
        migrations.CreateModel(
            name='Earth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, null=True, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a')),
                ('SEOTitle', models.TextField(blank=True, null=True, verbose_name='SEO Title')),
                ('SEOKeywords', models.TextField(blank=True, null=True, verbose_name='SEO Keywords')),
                ('SEODescription', models.TextField(blank=True, null=True, verbose_name='SEO Description')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='\u0426\u0435\u043d\u0430')),
                ('address', models.CharField(blank=True, max_length=250, null=True, verbose_name='\u0410\u0434\u0440\u0435\u0441')),
                ('type_area', models.CharField(blank=True, choices=[('for_building', '\u041f\u043e\u0434 \u0437\u0430\u0441\u0442\u0440\u043e\u0439\u043a\u0443'), ('gardening', '\u0421\u0430\u0434\u043e\u0432\u043e\u0434\u0441\u0442\u0432\u043e'), ('commercial', '\u041a\u043e\u043c\u0435\u0440\u0447\u0435\u0441\u043a\u0430\u044f'), ('handed', '\u0414\u043e\u043c \u0441\u0434\u0430\u043d')], max_length=50, null=True, verbose_name='\u0422\u0438\u043f \u0423\u0447\u0430\u0441\u0442\u043a\u0430')),
                ('to_city', models.IntegerField(blank=True, null=True, verbose_name='\u0414\u043e \u0433\u043e\u0440\u043e\u0434\u0430, \u043a\u043c')),
                ('communication', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('water', '\u0412\u043e\u0434\u0430'), ('gas', '\u0413\u0430\u0437'), ('sewage', '\u041a\u0430\u043d\u0430\u043b\u0438\u0437\u0430\u0446\u0438\u044f'), ('electricity', '\u042d\u043b\u0435\u043a\u0442\u0440\u0438\u0447\u0435\u0441\u0442\u0432\u043e')], max_length=50, null=True, verbose_name='\u041a\u043e\u043c\u043c\u0443\u043d\u0438\u043a\u0430\u0446\u0438\u0438')),
                ('structure_house', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('house', '\u0414\u043e\u043c'), ('cuisine', '\u041b\u0435\u0442\u043d\u0430\u044f \u043a\u0443\u0445\u043d\u044f'), ('barn', '\u0421\u0430\u0440\u0430\u0439'), ('pool', '\u0411\u0430\u0441\u0441\u0435\u0439\u043d')], max_length=50, null=True, verbose_name='\u0421\u0442\u0440\u043e\u0435\u043d\u0438\u0435 \u0434\u043e\u043c\u0430')),
                ('area', models.IntegerField(blank=True, null=True, verbose_name='\u041f\u043b\u043e\u0449\u0430\u0434\u044c')),
                ('contact_name', models.CharField(blank=True, max_length=250, null=True, verbose_name='\u041a\u043e\u043d\u0442\u0430\u043a\u0442\u043d\u043e\u0435 \u043b\u0438\u0446\u043e')),
                ('phone', models.CharField(blank=True, max_length=250, null=True, verbose_name='\u0422\u0435\u043b\u0435\u0444\u043e\u043d')),
                ('description', models.TextField(blank=True, verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435')),
                ('geo', models.TextField(blank=True, verbose_name='\u041d\u0430 \u043a\u0430\u0440\u0442\u0435')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('when_create', models.DateTimeField(auto_now_add=True, verbose_name='\u0414\u0430\u0442\u0430 \u043f\u0443\u0431\u043b\u0438\u043a\u0430\u0446\u0438\u0438')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='\u0414\u0430\u0442\u0430 \u0440\u0435\u0434\u0430\u043a\u0442\u0438\u0440\u043e\u0432\u0430\u043d\u0438\u044f')),
            ],
            options={
                'ordering': ['-when_create'],
                'verbose_name': '\u0417\u0435\u043c\u043b\u044f',
                'verbose_name_plural': '\u0417\u0435\u043c\u043b\u044f',
            },
        ),
        migrations.CreateModel(
            name='EarthDistrict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
            ],
            options={
                'verbose_name': '\u0420\u0430\u0439\u043e\u043d \u0434\u043b\u044f \u0437\u0435\u043c\u043b\u044f',
                'verbose_name_plural': '\u0420\u0430\u0439\u043e\u043d\u044b \u0434\u043b\u044f \u0437\u0435\u043c\u043b\u044f',
            },
        ),
        migrations.CreateModel(
            name='Infrastructure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='icons/%Y/%m/%d/', verbose_name='\u0424\u043e\u0442\u043e')),
                ('title', models.CharField(max_length=250, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a')),
            ],
            options={
                'ordering': ['-id'],
                'verbose_name': '\u0418\u043d\u0444\u0440\u0430\u0441\u0442\u0440\u0443\u043a\u0442\u0443\u0440\u0430',
                'verbose_name_plural': '\u0418\u043d\u0444\u0440\u0430\u0441\u0442\u0440\u0443\u043a\u0442\u0443\u0440\u0430',
            },
        ),
        migrations.CreateModel(
            name='NewBuilding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(allow_unicode=True, unique=True, verbose_name='URL')),
                ('title', models.CharField(blank=True, max_length=250, null=True, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a')),
                ('name', models.CharField(blank=True, max_length=250, null=True, verbose_name='\u0418\u043c\u044f')),
                ('phone', models.CharField(blank=True, max_length=250, null=True, verbose_name='\u0422\u0435\u043b\u0435\u0444\u043e\u043d')),
                ('is_enable', models.BooleanField(default=True, help_text='\u0430\u043a\u0442\u0438\u0432\u043d\u044b\u0439 \u0438\u043b\u0438 \u043d\u0435 \u0430\u043a\u0442\u0438\u0432\u043d\u044b\u0439', verbose_name='\u0421\u0442\u0430\u0442\u0443\u0441')),
                ('SEOTitle', models.TextField(blank=True, null=True, verbose_name='SEO Title')),
                ('SEOKeywords', models.TextField(blank=True, null=True, verbose_name='SEO Keywords')),
                ('SEODescription', models.TextField(blank=True, null=True, verbose_name='SEO Description')),
                ('address', models.CharField(blank=True, max_length=250, null=True, verbose_name='\u0410\u0434\u0440\u0435\u0441')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='\u0426\u0435\u043d\u0430 \u0437\u0430 \u043c.\u043a\u0432')),
                ('price_object', models.IntegerField(blank=True, null=True, verbose_name='\u0426\u0435\u043d\u0430 \u0437\u0430 \u043e\u0431\u044a\u0435\u043a\u0442')),
                ('date_delivery', models.DateField(blank=True, null=True, verbose_name='\u0414\u0430\u0442\u0430 \u0441\u0434\u0430\u0447\u0438')),
                ('point', models.IntegerField(blank=True, null=True, verbose_name='\u0411\u0430\u043b\u044b')),
                ('description', models.TextField(blank=True, verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435')),
                ('panorama', models.TextField(blank=True, verbose_name='\u041f\u0430\u043d\u043e\u0440\u0430\u043c\u0430')),
                ('geo', models.TextField(blank=True, verbose_name='\u041d\u0430 \u043a\u0430\u0440\u0442\u0435')),
                ('views', models.IntegerField(default=0, verbose_name='\u041f\u0440\u043e\u0441\u043c\u043e\u0442\u0440\u044b')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('when_create', models.DateTimeField(auto_now_add=True, verbose_name='\u0414\u0430\u0442\u0430 \u043f\u0443\u0431\u043b\u0438\u043a\u0430\u0446\u0438\u0438')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='\u0414\u0430\u0442\u0430 \u0440\u0435\u0434\u0430\u043a\u0442\u0438\u0440\u043e\u0432\u0430\u043d\u0438\u044f')),
                ('image', models.ImageField(blank=True, upload_to='background/%Y/%m/%d/', verbose_name='\u0424\u043e\u0442\u043e')),
                ('parade', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='\u041f\u0430\u0440\u0430\u0434\u043d\u044b\u0445')),
                ('storeys', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='\u042d\u0442\u0430\u0436\u043d\u043e\u0441\u0442\u044c')),
                ('parking_places', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='\u041f\u0430\u0440\u043a\u043e\u0432\u043e\u0447\u043d\u044b\u0445 \u043c\u0435\u0441\u0442')),
                ('total_area', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='\u041e\u0431\u0449\u0430\u044f \u043f\u043b\u043e\u0449\u0430\u0434\u044c')),
                ('class_house', models.CharField(blank=True, max_length=20, null=True, verbose_name='\u041a\u043b\u0430\u0441 \u0434\u043e\u043c\u0430')),
                ('start_construction', models.DateField(blank=True, null=True, verbose_name='\u041d\u0430\u0447\u0430\u043b\u043e \u0441\u0442\u0440\u043e\u0438\u0442\u0435\u043b\u044c\u0441\u0442\u0432\u0430')),
                ('end_construction', models.DateField(blank=True, null=True, verbose_name='\u041a\u043e\u043d\u0435\u0446 \u0441\u0442\u0440\u043e\u0438\u0442\u0435\u043b\u044c\u0441\u0442\u0432\u0430')),
                ('accommodations', models.ManyToManyField(blank=True, related_name='newbuilding', to='rieltor_object.Accommodations')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='newbuilding', to='rieltor_object.District', verbose_name='\u0420\u0430\u0439\u043e\u043d')),
                ('infrastructures', models.ManyToManyField(blank=True, related_name='newbuilding', to='rieltor_object.Infrastructure')),
            ],
            options={
                'ordering': ['-when_create'],
                'verbose_name': '\u041d\u043e\u0432\u043e\u0441\u0442\u0440\u043e\u0438',
                'verbose_name_plural': '\u041d\u043e\u0432\u043e\u0441\u0442\u0440\u043e\u0438',
            },
        ),
        migrations.CreateModel(
            name='Ofice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, null=True, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a')),
                ('SEOTitle', models.TextField(blank=True, null=True, verbose_name='SEO Title')),
                ('SEOKeywords', models.TextField(blank=True, null=True, verbose_name='SEO Keywords')),
                ('SEODescription', models.TextField(blank=True, null=True, verbose_name='SEO Description')),
                ('address', models.CharField(blank=True, max_length=250, null=True, verbose_name='\u0410\u0434\u0440\u0435\u0441')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='\u0426\u0435\u043d\u0430')),
                ('type_deal', models.CharField(blank=True, choices=[('rent', '\u0410\u0440\u0435\u043d\u0434\u0430'), ('sale', '\u041f\u0440\u043e\u0434\u0430\u0436\u0430')], max_length=20, null=True, verbose_name='\u0422\u0438\u043f')),
                ('appointment', models.CharField(blank=True, choices=[('apartment', '\u041a\u0432\u0430\u0440\u0442\u0438\u0440\u0430'), ('house', '\u0414\u043e\u043c')], max_length=20, null=True, verbose_name='\u041d\u0430\u0437\u043d\u0430\u0447\u0435\u043d\u0438\u0435')),
                ('footage', models.IntegerField(blank=True, null=True, verbose_name='\u041f\u043b\u043e\u0449\u0430\u0434\u044c')),
                ('rooms', models.IntegerField(blank=True, null=True, verbose_name='\u041a\u043e\u043c\u043d\u0430\u0442')),
                ('point', models.IntegerField(blank=True, null=True, verbose_name='\u0411\u0430\u043b\u044b')),
                ('when_create', models.DateTimeField(auto_now_add=True, verbose_name='\u0414\u0430\u0442\u0430 \u043f\u0443\u0431\u043b\u0438\u043a\u0430\u0446\u0438\u0438')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='\u0414\u0430\u0442\u0430 \u0440\u0435\u0434\u0430\u043a\u0442\u0438\u0440\u043e\u0432\u0430\u043d\u0438\u044f')),
                ('location', models.CharField(blank=True, choices=[('facade', '\u0424\u0430\u0441\u0430\u0434'), ('from_yard', '\u0414\u0432\u043e\u0440\u043e\u0432\u043e\u0439'), ('business_center', '\u0411\u0438\u0437\u043d\u0435\u0441-\u0446\u0435\u043d\u0442\u0440')], max_length=20, null=True, verbose_name='\u0420\u0430\u0441\u043f\u043e\u043b\u043e\u0436\u0435\u043d\u0438\u0435')),
                ('floor', models.CharField(blank=True, choices=[('first', '1-\u0439'), ('base', '\u0426\u043e\u043a\u043e\u043b\u044c'), ('mezzanine', '\u0411\u0435\u043b\u044c\u044d\u0442\u0430\u0436')], max_length=20, null=True, verbose_name='\u042d\u0442\u0430\u0436')),
                ('entrance', models.CharField(blank=True, choices=[('facade', '\u0424\u0430\u0441\u0430\u0434'), ('from_yard', '\u0421\u043e \u0434\u0432\u043e\u0440\u0430'), ('with_grand', '\u0421 \u043f\u0430\u0440\u0430\u0434\u043d\u043e\u0439')], max_length=20, null=True, verbose_name='\u0412\u0445\u043e\u0434')),
                ('status', models.CharField(blank=True, choices=[('vip', 'VIP'), ('default', '\u041e\u0431\u044b\u0447\u043d\u043e\u0435'), ('short', '\u041a\u0440\u0430\u0442\u043a\u043e\u0435')], max_length=20, null=True, verbose_name='\u0421\u0442\u0430\u0442\u0443\u0441')),
                ('description', models.TextField(blank=True, verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435')),
                ('panorama', models.TextField(blank=True, verbose_name='\u041f\u0430\u043d\u043e\u0440\u0430\u043c\u0430')),
                ('geo', models.TextField(blank=True, verbose_name='\u041d\u0430 \u043a\u0430\u0440\u0442\u0435')),
                ('views', models.IntegerField(default=0, verbose_name='\u041f\u0440\u043e\u0441\u043c\u043e\u0442\u0440\u044b')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ofice', to='rieltor_object.District', verbose_name='\u0420\u0430\u0439\u043e\u043d')),
            ],
            options={
                'ordering': ['-when_create'],
                'verbose_name': '\u041e\u0444\u0438\u0441\u044b \u0438 \u043c\u0430\u0433\u0430\u0437\u0438\u043d\u044b',
                'verbose_name_plural': '\u041e\u0444\u0438\u0441\u044b \u0438 \u043c\u0430\u0433\u0430\u0437\u0438\u043d\u044b',
            },
        ),
        migrations.AddField(
            model_name='earth',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='earth', to='rieltor_object.EarthDistrict', verbose_name='\u0420\u0430\u0439\u043e\u043d'),
        ),
        migrations.AddField(
            model_name='daily',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily', to='rieltor_object.DailyDistrict', verbose_name='\u0420\u0430\u0439\u043e\u043d'),
        ),
        migrations.AddField(
            model_name='daily',
            name='infrastructures',
            field=models.ManyToManyField(blank=True, related_name='daily', to='rieltor_object.Infrastructure'),
        ),
        migrations.AddField(
            model_name='building',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='building', to='rieltor_object.District', verbose_name='\u0420\u0430\u0439\u043e\u043d'),
        ),
        migrations.AddField(
            model_name='building',
            name='newbuilding',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='building', to='rieltor_object.NewBuilding', verbose_name='\u041d\u043e\u0432\u043e\u0441\u0442\u0440\u043e\u0438'),
        ),
    ]
