# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 22:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rieltor_object', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newbuilding',
            name='is_enable',
            field=models.BooleanField(default=True, help_text='\u043d\u0443\u0436\u043d\u043e \u0441\u043e\u0445\u0440\u0430\u043d\u044f\u0442\u044c', verbose_name='\u0421\u0442\u0430\u0442\u0443\u0441'),
        ),
        migrations.AlterField(
            model_name='ofice',
            name='appointment',
            field=models.CharField(blank=True, choices=[('office', '\u041e\u0444\u0438\u0441'), ('shop', '\u041c\u0430\u0433\u0430\u0437\u0438\u043d')], max_length=20, null=True, verbose_name='\u041d\u0430\u0437\u043d\u0430\u0447\u0435\u043d\u0438\u0435'),
        ),
    ]
