# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-09 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rieltor_object', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='point',
            field=models.IntegerField(blank=True, verbose_name='\u0411\u0430\u043b\u044b'),
        ),
    ]
