# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-10 00:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rieltor_object', '0002_auto_20170508_0154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='entrance',
        ),
        migrations.RemoveField(
            model_name='building',
            name='location',
        ),
        migrations.RemoveField(
            model_name='building',
            name='status',
        ),
        migrations.AddField(
            model_name='building',
            name='is_short',
            field=models.BooleanField(default=False, verbose_name='\u041a\u0440\u0430\u0442\u043a\u043e\u0435'),
        ),
        migrations.AddField(
            model_name='building',
            name='is_vip',
            field=models.BooleanField(default=False, verbose_name='VIP'),
        ),
        migrations.AddField(
            model_name='building',
            name='layout',
            field=models.CharField(blank=True, choices=[('related', '\u0421\u043c\u0435\u0436\u043d\u044b\u0435'), ('separate', '\u0420\u0430\u0437\u0434\u0435\u043b\u044c\u043d\u044b\u0435'), ('related-separate', '\u0421\u043c\u0435\u0436\u043d\u043e-\u0440\u0430\u0437\u0434\u0435\u043b\u044c\u043d\u044b\u0435')], max_length=20, null=True, verbose_name='\u041f\u043b\u0430\u043d\u0438\u0440\u043e\u0432\u043a\u0430'),
        ),
        migrations.AddField(
            model_name='building',
            name='price_nac',
            field=models.IntegerField(blank=True, null=True, verbose_name='\u0426\u0435\u043d\u0430, \u043d\u0430\u0446.\u0432\u0430\u043b.'),
        ),
        migrations.AddField(
            model_name='building',
            name='video',
            field=models.TextField(blank=True, verbose_name='\u041a\u043e\u0434 \u0432\u0438\u0434\u0435\u043e'),
        ),
        migrations.AlterField(
            model_name='building',
            name='floor',
            field=models.IntegerField(blank=True, null=True, verbose_name='\u042d\u0442\u0430\u0436'),
        ),
        migrations.AlterField(
            model_name='building',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='\u0426\u0435\u043d\u0430, $'),
        ),
    ]
