# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-10 00:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rieltor_object', '0003_auto_20170510_0301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='geo',
        ),
    ]
