# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-09 21:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rieltor_object', '0003_auto_20170409_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='SEODescription',
            field=models.TextField(blank=True, null=True, verbose_name='SEO Description'),
        ),
        migrations.AddField(
            model_name='building',
            name='SEOKeywords',
            field=models.TextField(blank=True, null=True, verbose_name='SEO Keywords'),
        ),
        migrations.AddField(
            model_name='building',
            name='SEOTitle',
            field=models.TextField(blank=True, null=True, verbose_name='SEO Title'),
        ),
        migrations.AddField(
            model_name='building',
            name='title',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a'),
        ),
    ]
