# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-09 23:45
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('rieltor_object', '0004_auto_20170410_0048'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
