# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-10 00:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rieltor_object', '0005_building_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='building', to='rieltor_object.District', verbose_name='\u0420\u0430\u0439\u043e\u043d'),
        ),
    ]
