# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-10 00:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rieltor_object', '0006_auto_20170410_0301'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='building',
            options={'ordering': ['-when_create'], 'verbose_name': '\u041a\u0432\u0430\u0440\u0442\u0438\u0440\u044b \u0438 \u0414\u043e\u043c\u0430', 'verbose_name_plural': '\u041a\u0432\u0430\u0440\u0442\u0438\u0440\u044b \u0438 \u0414\u043e\u043c\u0430'},
        ),
    ]
