# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-10 01:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rieltor_object', '0007_auto_20170410_0333'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'VIP'), (2, '\u041e\u0431\u044b\u0447\u043d\u043e\u0435'), (3, '\u041a\u0440\u0430\u0442\u043a\u043e\u0435')], null=True, verbose_name='\u0421\u0442\u0430\u0442\u0443\u0441'),
        ),
        migrations.AlterField(
            model_name='building',
            name='entrance',
            field=models.IntegerField(blank=True, choices=[(1, '\u0424\u0430\u0441\u0430\u0434'), (2, '\u0421\u043e \u0434\u0432\u043e\u0440\u0430'), (3, '\u0421 \u043f\u0430\u0440\u0430\u0434\u043d\u043e\u0439')], verbose_name='\u0412\u0445\u043e\u0434'),
        ),
    ]
