# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-10 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rieltor_object', '0008_auto_20170410_0452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='footage',
            field=models.IntegerField(blank=True, null=True, verbose_name='\u041f\u043b\u043e\u0449\u0430\u0434\u044c'),
        ),
        migrations.AlterField(
            model_name='building',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='\u0426\u0435\u043d\u0430'),
        ),
    ]
