# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-15 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rieltor_object', '0009_remove_earth_contact_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='image',
            field=models.ImageField(blank=True, upload_to='background/%Y/%m/%d/', verbose_name='\u0424\u043e\u0442\u043e'),
        ),
        migrations.AddField(
            model_name='ofice',
            name='image',
            field=models.ImageField(blank=True, upload_to='background/%Y/%m/%d/', verbose_name='\u0424\u043e\u0442\u043e'),
        ),
    ]
