# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-10 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rieltor_object', '0009_auto_20170410_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='point',
            field=models.IntegerField(blank=True, null=True, verbose_name='\u0411\u0430\u043b\u044b'),
        ),
        migrations.AlterField(
            model_name='building',
            name='rooms',
            field=models.IntegerField(blank=True, null=True, verbose_name='\u041a\u043e\u043c\u043d\u0430\u0442'),
        ),
    ]
