# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-10 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rieltor_object', '0010_auto_20170410_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='appointment',
            field=models.IntegerField(blank=True, choices=[(1, '\u041a\u0432\u0430\u0440\u0442\u0438\u0440\u0430'), (2, '\u0414\u043e\u043c')], null=True, verbose_name='\u041d\u0430\u0437\u043d\u0430\u0447\u0435\u043d\u0438\u0435'),
        ),
        migrations.AlterField(
            model_name='building',
            name='entrance',
            field=models.IntegerField(blank=True, choices=[(1, '\u0424\u0430\u0441\u0430\u0434'), (2, '\u0421\u043e \u0434\u0432\u043e\u0440\u0430'), (3, '\u0421 \u043f\u0430\u0440\u0430\u0434\u043d\u043e\u0439')], null=True, verbose_name='\u0412\u0445\u043e\u0434'),
        ),
        migrations.AlterField(
            model_name='building',
            name='floor',
            field=models.IntegerField(blank=True, choices=[(1, '1-\u0439'), (2, '\u0426\u043e\u043a\u043e\u043b\u044c'), (3, '\u0411\u0435\u043b\u044c\u044d\u0442\u0430\u0436')], null=True, verbose_name='\u042d\u0442\u0430\u0436'),
        ),
        migrations.AlterField(
            model_name='building',
            name='location',
            field=models.IntegerField(blank=True, choices=[(1, '\u0424\u0430\u0441\u0430\u0434'), (2, '\u0414\u0432\u043e\u0440\u043e\u0432\u043e\u0439'), (3, '\u0411\u0438\u0437\u043d\u0435\u0441-\u0446\u0435\u043d\u0442\u0440')], null=True, verbose_name='\u0420\u0430\u0441\u043f\u043e\u043b\u043e\u0436\u0435\u043d\u0438\u0435'),
        ),
        migrations.AlterField(
            model_name='building',
            name='type_deal',
            field=models.IntegerField(blank=True, choices=[(1, '\u0410\u0440\u0435\u043d\u0434\u0430'), (2, '\u041f\u0440\u043e\u0434\u0430\u0436\u0430')], null=True, verbose_name='\u0422\u0438\u043f'),
        ),
    ]
