# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 12:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('rieltor_object', '0011_auto_20170410_2032'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ofis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, null=True, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a')),
                ('SEOTitle', models.TextField(blank=True, null=True, verbose_name='SEO Title')),
                ('SEOKeywords', models.TextField(blank=True, null=True, verbose_name='SEO Keywords')),
                ('SEODescription', models.TextField(blank=True, null=True, verbose_name='SEO Description')),
                ('address', models.CharField(blank=True, max_length=250, null=True, verbose_name='\u0410\u0434\u0440\u0435\u0441')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='\u0426\u0435\u043d\u0430')),
                ('type_deal', models.IntegerField(blank=True, choices=[(1, '\u0410\u0440\u0435\u043d\u0434\u0430'), (2, '\u041f\u0440\u043e\u0434\u0430\u0436\u0430')], null=True, verbose_name='\u0422\u0438\u043f')),
                ('appointment', models.IntegerField(blank=True, choices=[(1, '\u041a\u0432\u0430\u0440\u0442\u0438\u0440\u0430'), (2, '\u0414\u043e\u043c')], null=True, verbose_name='\u041d\u0430\u0437\u043d\u0430\u0447\u0435\u043d\u0438\u0435')),
                ('footage', models.IntegerField(blank=True, null=True, verbose_name='\u041f\u043b\u043e\u0449\u0430\u0434\u044c')),
                ('rooms', models.IntegerField(blank=True, null=True, verbose_name='\u041a\u043e\u043c\u043d\u0430\u0442')),
                ('point', models.IntegerField(blank=True, null=True, verbose_name='\u0411\u0430\u043b\u044b')),
                ('when_create', models.DateTimeField(auto_now_add=True, verbose_name='\u0414\u0430\u0442\u0430 \u043f\u0443\u0431\u043b\u0438\u043a\u0430\u0446\u0438\u0438')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='\u0414\u0430\u0442\u0430 \u0440\u0435\u0434\u0430\u043a\u0442\u0438\u0440\u043e\u0432\u0430\u043d\u0438\u044f')),
                ('location', models.IntegerField(blank=True, choices=[(1, '\u0424\u0430\u0441\u0430\u0434'), (2, '\u0414\u0432\u043e\u0440\u043e\u0432\u043e\u0439'), (3, '\u0411\u0438\u0437\u043d\u0435\u0441-\u0446\u0435\u043d\u0442\u0440')], null=True, verbose_name='\u0420\u0430\u0441\u043f\u043e\u043b\u043e\u0436\u0435\u043d\u0438\u0435')),
                ('floor', models.IntegerField(blank=True, choices=[(1, '1-\u0439'), (2, '\u0426\u043e\u043a\u043e\u043b\u044c'), (3, '\u0411\u0435\u043b\u044c\u044d\u0442\u0430\u0436')], null=True, verbose_name='\u042d\u0442\u0430\u0436')),
                ('entrance', models.IntegerField(blank=True, choices=[(1, '\u0424\u0430\u0441\u0430\u0434'), (2, '\u0421\u043e \u0434\u0432\u043e\u0440\u0430'), (3, '\u0421 \u043f\u0430\u0440\u0430\u0434\u043d\u043e\u0439')], null=True, verbose_name='\u0412\u0445\u043e\u0434')),
                ('status', models.IntegerField(blank=True, choices=[(1, 'VIP'), (2, '\u041e\u0431\u044b\u0447\u043d\u043e\u0435'), (3, '\u041a\u0440\u0430\u0442\u043a\u043e\u0435')], null=True, verbose_name='\u0421\u0442\u0430\u0442\u0443\u0441')),
                ('description', models.TextField(blank=True, verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435')),
                ('panorama', models.TextField(blank=True, verbose_name='\u041f\u0430\u043d\u043e\u0440\u0430\u043c\u0430')),
                ('geo', models.TextField(blank=True, verbose_name='\u041d\u0430 \u043a\u0430\u0440\u0442\u0435')),
                ('views', models.IntegerField(default=0, verbose_name='\u041f\u0440\u043e\u0441\u043c\u043e\u0442\u0440\u044b')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ofis', to='rieltor_object.District', verbose_name='\u0420\u0430\u0439\u043e\u043d')),
            ],
            options={
                'ordering': ['-when_create'],
                'verbose_name': '\u041e\u0444\u0438\u0441\u044b \u0438 \u043c\u0430\u0433\u0430\u0437\u0438\u043d\u044b',
                'verbose_name_plural': '\u041e\u0444\u0438\u0441\u044b \u0438 \u043c\u0430\u0433\u0430\u0437\u0438\u043d\u044b',
            },
        ),
    ]
