# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-17 07:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rieltor_object', '0011_auto_20170517_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='custom_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='daily',
            name='custom_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='earth',
            name='custom_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='newbuilding',
            name='custom_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ofice',
            name='custom_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='ID'),
        ),
    ]
