# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-21 23:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rieltor_object', '0012_auto_20170517_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='period',
            field=models.CharField(blank=True, choices=[('\u043a\u043e\u0440\u043e\u0442\u043a\u0438\u0439', '\u043a\u043e\u0440\u043e\u0442\u043a\u0438\u0439'), ('\u043c\u0435\u0441\u044f\u0446', '\u043c\u0435\u0441\u044f\u0446'), ('\u0434\u043e\u043b\u0433\u0438\u0439 \u0441\u0440\u043e\u043a (6\u043c\u0435\u0441)', '\u0434\u043e\u043b\u0433\u0438\u0439 \u0441\u0440\u043e\u043a (6\u043c\u0435\u0441)')], max_length=50, null=True, verbose_name='\u041f\u0435\u0440\u0438\u043e\u0434'),
        ),
        migrations.AddField(
            model_name='building',
            name='proposal',
            field=models.CharField(blank=True, choices=[('\u043a\u043e\u043d\u0434\u043e', '\u043a\u043e\u043d\u0434\u043e'), ('\u043a\u0432\u0430\u0440\u0442\u0438\u0440\u044b', '\u043a\u0432\u0430\u0440\u0442\u0438\u0440\u044b'), ('\u0432\u0438\u043b\u043b\u044b', '\u0432\u0438\u043b\u043b\u044b')], max_length=50, null=True, verbose_name='\u041f\u0440\u0435\u0434\u043b\u043e\u0436\u0435\u043d\u0438\u0435'),
        ),
    ]
