# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-21 23:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rieltor_object', '0013_auto_20170522_0205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='period',
            field=models.CharField(blank=True, choices=[('short', '\u043a\u043e\u0440\u043e\u0442\u043a\u0438\u0439'), ('month', '\u043c\u0435\u0441\u044f\u0446'), ('long', '\u0434\u043e\u043b\u0433\u0438\u0439 \u0441\u0440\u043e\u043a (6\u043c\u0435\u0441)')], max_length=50, null=True, verbose_name='\u041f\u0435\u0440\u0438\u043e\u0434'),
        ),
        migrations.AlterField(
            model_name='building',
            name='proposal',
            field=models.CharField(blank=True, choices=[('condo', '\u043a\u043e\u043d\u0434\u043e'), ('appartment', '\u043a\u0432\u0430\u0440\u0442\u0438\u0440\u044b'), ('villas', '\u0432\u0438\u043b\u043b\u044b')], max_length=50, null=True, verbose_name='\u041f\u0440\u0435\u0434\u043b\u043e\u0436\u0435\u043d\u0438\u0435'),
        ),
    ]
