# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 14:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('rieltor_object', '0013_auto_20170418_1528'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewBuilding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, null=True, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a')),
                ('SEOTitle', models.TextField(blank=True, null=True, verbose_name='SEO Title')),
                ('SEOKeywords', models.TextField(blank=True, null=True, verbose_name='SEO Keywords')),
                ('SEODescription', models.TextField(blank=True, null=True, verbose_name='SEO Description')),
                ('address', models.CharField(blank=True, max_length=250, null=True, verbose_name='\u0410\u0434\u0440\u0435\u0441')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='\u0426\u0435\u043d\u0430 \u0437\u0430 \u043c.\u043a\u0432')),
                ('date_delivery', models.DateField(blank=True, null=True, verbose_name='\u0414\u0430\u0442\u0430 \u0441\u0434\u0430\u0447\u0438')),
                ('point', models.IntegerField(blank=True, null=True, verbose_name='\u0411\u0430\u043b\u044b')),
                ('description', models.TextField(blank=True, verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435')),
                ('panorama', models.TextField(blank=True, verbose_name='\u041f\u0430\u043d\u043e\u0440\u0430\u043c\u0430')),
                ('geo', models.TextField(blank=True, verbose_name='\u041d\u0430 \u043a\u0430\u0440\u0442\u0435')),
                ('views', models.IntegerField(default=0, verbose_name='\u041f\u0440\u043e\u0441\u043c\u043e\u0442\u0440\u044b')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('when_create', models.DateTimeField(auto_now_add=True, verbose_name='\u0414\u0430\u0442\u0430 \u043f\u0443\u0431\u043b\u0438\u043a\u0430\u0446\u0438\u0438')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='\u0414\u0430\u0442\u0430 \u0440\u0435\u0434\u0430\u043a\u0442\u0438\u0440\u043e\u0432\u0430\u043d\u0438\u044f')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='newbuilding', to='rieltor_object.District', verbose_name='\u0420\u0430\u0439\u043e\u043d')),
            ],
        ),
    ]
