# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 14:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rieltor_object', '0014_newbuilding'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='newbuilding',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='building', to='rieltor_object.NewBuilding', verbose_name='\u041d\u043e\u0432\u043e\u0441\u0442\u0440\u043e\u0438'),
        ),
    ]
