# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 01:21
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rieltor_object', '0014_auto_20170522_0243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435'),
        ),
    ]
