# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 16:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('rieltor_object', '0015_building_newbuilding'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accommodations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='icons/%Y/%m/%d/', verbose_name='\u0424\u043e\u0442\u043e')),
                ('title', models.CharField(max_length=250, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a')),
                ('description', models.CharField(max_length=250, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': '\u0423\u0441\u043b\u043e\u0432\u0438\u044f \u043f\u0440\u043e\u0436\u0438\u0432\u0430\u043d\u0438\u044f',
                'verbose_name_plural': '\u0423\u0441\u043b\u043e\u0432\u0438\u044f \u043f\u0440\u043e\u0436\u0438\u0432\u0430\u043d\u0438\u044f',
            },
        ),
        migrations.CreateModel(
            name='Infrastructure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='icons/%Y/%m/%d/', verbose_name='\u0424\u043e\u0442\u043e')),
                ('title', models.CharField(max_length=250, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': '\u0418\u043d\u0444\u0440\u0430\u0441\u0442\u0440\u0443\u043a\u0442\u0443\u0440\u0430',
                'verbose_name_plural': '\u0418\u043d\u0444\u0440\u0430\u0441\u0442\u0440\u0443\u043a\u0442\u0443\u0440\u0430',
            },
        ),
        migrations.AlterModelOptions(
            name='newbuilding',
            options={'ordering': ['-when_create'], 'verbose_name': '\u041d\u043e\u0432\u043e\u0441\u0442\u0440\u043e\u0438', 'verbose_name_plural': '\u041d\u043e\u0432\u043e\u0441\u0442\u0440\u043e\u0438'},
        ),
        migrations.AddField(
            model_name='newbuilding',
            name='class_house',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='\u041a\u043b\u0430\u0441 \u0434\u043e\u043c\u0430'),
        ),
        migrations.AddField(
            model_name='newbuilding',
            name='end_construction',
            field=models.DateField(blank=True, null=True, verbose_name='\u041a\u043e\u043d\u0435\u0446 \u0441\u0442\u0440\u043e\u0438\u0442\u0435\u043b\u044c\u0441\u0442\u0432\u0430'),
        ),
        migrations.AddField(
            model_name='newbuilding',
            name='image',
            field=models.ImageField(blank=True, upload_to='background/%Y/%m/%d/', verbose_name='\u0424\u043e\u0442\u043e'),
        ),
        migrations.AddField(
            model_name='newbuilding',
            name='is_enable',
            field=models.BooleanField(default=True, help_text='\u0430\u043a\u0442\u0438\u0432\u043d\u044b\u0439 \u0438\u043b\u0438 \u043d\u0435 \u0430\u043a\u0442\u0438\u0432\u043d\u044b\u0439', verbose_name='\u0421\u0442\u0430\u0442\u0443\u0441'),
        ),
        migrations.AddField(
            model_name='newbuilding',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='\u0418\u043c\u044f'),
        ),
        migrations.AddField(
            model_name='newbuilding',
            name='parade',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='\u041f\u0430\u0440\u0430\u0434\u043d\u044b\u0445'),
        ),
        migrations.AddField(
            model_name='newbuilding',
            name='parking_places',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='\u041f\u0430\u0440\u043a\u043e\u0432\u043e\u0447\u043d\u044b\u0445 \u043c\u0435\u0441\u0442'),
        ),
        migrations.AddField(
            model_name='newbuilding',
            name='phone',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='\u0422\u0435\u043b\u0435\u0444\u043e\u043d'),
        ),
        migrations.AddField(
            model_name='newbuilding',
            name='slug',
            field=models.SlugField(allow_unicode=True, default=1, unique=True, verbose_name='URL'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newbuilding',
            name='start_construction',
            field=models.DateField(blank=True, null=True, verbose_name='\u041d\u0430\u0447\u0430\u043b\u043e \u0441\u0442\u0440\u043e\u0438\u0442\u0435\u043b\u044c\u0441\u0442\u0432\u0430'),
        ),
        migrations.AddField(
            model_name='newbuilding',
            name='storeys',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='\u042d\u0442\u0430\u0436\u043d\u043e\u0441\u0442\u044c'),
        ),
        migrations.AddField(
            model_name='newbuilding',
            name='total_area',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='\u041e\u0431\u0449\u0430\u044f \u043f\u043b\u043e\u0449\u0430\u0434\u044c'),
        ),
    ]
