# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rieltor_object', '0016_auto_20170418_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodations',
            name='description',
            field=models.CharField(max_length=250, verbose_name='\u041e\u043e\u043f\u0438\u0441\u0430\u043d\u0438\u0435'),
        ),
    ]
