# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 02:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rieltor_object', '0016_auto_20170524_0438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daily',
            name='geo',
        ),
        migrations.AddField(
            model_name='daily',
            name='video',
            field=models.TextField(blank=True, verbose_name='\u041a\u043e\u0434 \u0432\u0438\u0434\u0435\u043e'),
        ),
    ]
