# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rieltor_object', '0017_auto_20170529_0536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ofice',
            name='status',
        ),
        migrations.AddField(
            model_name='ofice',
            name='is_short',
            field=models.BooleanField(default=False, verbose_name='\u041a\u0440\u0430\u0442\u043a\u043e\u0435'),
        ),
        migrations.AddField(
            model_name='ofice',
            name='is_vip',
            field=models.BooleanField(default=False, verbose_name='VIP'),
        ),
        migrations.AlterField(
            model_name='building',
            name='appointment',
            field=models.CharField(blank=True, choices=[('apartment', '\u041a\u0432\u0430\u0440\u0442\u0438\u0440\u0430'), ('house', '\u0414\u043e\u043c'), ('room', '\u041a\u043e\u043c\u043d\u0430\u0442\u0430')], max_length=20, null=True, verbose_name='\u041d\u0430\u0437\u043d\u0430\u0447\u0435\u043d\u0438\u0435'),
        ),
        migrations.AlterField(
            model_name='ofice',
            name='floor',
            field=models.CharField(blank=True, choices=[('first', '1-\u0439'), ('base', '\u0426\u043e\u043a\u043e\u043b\u044c'), ('mezzanine', '\u0411\u0435\u043b\u044c\u044d\u0442\u0430\u0436'), ('twofive', '2-5 \u044d\u0442\u0430\u0436')], max_length=20, null=True, verbose_name='\u042d\u0442\u0430\u0436'),
        ),
        migrations.AlterField(
            model_name='ofice',
            name='location',
            field=models.CharField(blank=True, choices=[('facade', '\u0424\u0430\u0441\u0430\u0434'), ('from_yard', '\u0414\u0432\u043e\u0440\u043e\u0432\u043e\u0439'), ('business_center', '\u0411\u0438\u0437\u043d\u0435\u0441-\u0446\u0435\u043d\u0442\u0440'), ('alonebuild', '\u041e\u0442\u0434\u0435\u043b\u044c\u043d\u043e\u0435 \u0437\u0434\u0430\u043d\u0438\u0435')], max_length=20, null=True, verbose_name='\u0420\u0430\u0441\u043f\u043e\u043b\u043e\u0436\u0435\u043d\u0438\u0435'),
        ),
    ]
