# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rieltor_object', '0018_auto_20170602_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='ofice',
            name='video',
            field=models.TextField(blank=True, verbose_name='\u041a\u043e\u0434 \u0432\u0438\u0434\u0435\u043e'),
        ),
    ]
