# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 14:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rieltor_object', '0019_ofice_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ofice',
            name='geo',
        ),
    ]
