# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-09 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rieltor_object', '0020_remove_ofice_geo'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='price_short',
            field=models.IntegerField(blank=True, null=True, verbose_name='\u0426\u0435\u043d\u0430'),
        ),
        migrations.AlterField(
            model_name='building',
            name='period',
            field=models.CharField(blank=True, choices=[('month', '\u043c\u0435\u0441\u044f\u0446'), ('long', '\u0434\u043e\u043b\u0433\u0438\u0439 \u0441\u0440\u043e\u043a')], max_length=50, null=True, verbose_name='\u041f\u0435\u0440\u0438\u043e\u0434'),
        ),
    ]
