# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rieltor_object', '0020_auto_20170420_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='appointment',
            field=models.CharField(blank=True, choices=[('\u041a\u0432\u0430\u0440\u0442\u0438\u0440\u0430', '\u041a\u0432\u0430\u0440\u0442\u0438\u0440\u0430'), ('\u0414\u043e\u043c', '\u0414\u043e\u043c')], max_length=20, null=True, verbose_name='\u041d\u0430\u0437\u043d\u0430\u0447\u0435\u043d\u0438\u0435'),
        ),
        migrations.AlterField(
            model_name='building',
            name='entrance',
            field=models.CharField(blank=True, choices=[('\u0424\u0430\u0441\u0430\u0434', '\u0424\u0430\u0441\u0430\u0434'), ('\u0421\u043e \u0434\u0432\u043e\u0440\u0430', '\u0421\u043e \u0434\u0432\u043e\u0440\u0430'), ('\u0421 \u043f\u0430\u0440\u0430\u0434\u043d\u043e\u0439', '\u0421 \u043f\u0430\u0440\u0430\u0434\u043d\u043e\u0439')], max_length=20, null=True, verbose_name='\u0412\u0445\u043e\u0434'),
        ),
        migrations.AlterField(
            model_name='building',
            name='floor',
            field=models.CharField(blank=True, choices=[('1-\u0439', '1-\u0439'), ('\u0426\u043e\u043a\u043e\u043b\u044c', '\u0426\u043e\u043a\u043e\u043b\u044c'), ('\u0411\u0435\u043b\u044c\u044d\u0442\u0430\u0436', '\u0411\u0435\u043b\u044c\u044d\u0442\u0430\u0436')], max_length=20, null=True, verbose_name='\u042d\u0442\u0430\u0436'),
        ),
        migrations.AlterField(
            model_name='building',
            name='location',
            field=models.CharField(blank=True, choices=[('\u0424\u0430\u0441\u0430\u0434', '\u0424\u0430\u0441\u0430\u0434'), ('\u0414\u0432\u043e\u0440\u043e\u0432\u043e\u0439', '\u0414\u0432\u043e\u0440\u043e\u0432\u043e\u0439'), ('\u0411\u0438\u0437\u043d\u0435\u0441-\u0446\u0435\u043d\u0442\u0440', '\u0411\u0438\u0437\u043d\u0435\u0441-\u0446\u0435\u043d\u0442\u0440')], max_length=20, null=True, verbose_name='\u0420\u0430\u0441\u043f\u043e\u043b\u043e\u0436\u0435\u043d\u0438\u0435'),
        ),
        migrations.AlterField(
            model_name='building',
            name='status',
            field=models.CharField(blank=True, choices=[('VIP', 'VIP'), ('\u041e\u0431\u044b\u0447\u043d\u043e\u0435', '\u041e\u0431\u044b\u0447\u043d\u043e\u0435'), ('\u041a\u0440\u0430\u0442\u043a\u043e\u0435', '\u041a\u0440\u0430\u0442\u043a\u043e\u0435')], max_length=20, null=True, verbose_name='\u0421\u0442\u0430\u0442\u0443\u0441'),
        ),
        migrations.AlterField(
            model_name='building',
            name='type_deal',
            field=models.CharField(blank=True, choices=[('\u0410\u0440\u0435\u043d\u0434\u0430', '\u0410\u0440\u0435\u043d\u0434\u0430'), ('\u041f\u0440\u043e\u0434\u0430\u0436\u0430', '\u041f\u0440\u043e\u0434\u0430\u0436\u0430')], max_length=20, null=True, verbose_name='\u0422\u0438\u043f'),
        ),
        migrations.AlterField(
            model_name='ofice',
            name='appointment',
            field=models.CharField(blank=True, choices=[('\u041a\u0432\u0430\u0440\u0442\u0438\u0440\u0430', '\u041a\u0432\u0430\u0440\u0442\u0438\u0440\u0430'), ('\u0414\u043e\u043c', '\u0414\u043e\u043c')], max_length=20, null=True, verbose_name='\u041d\u0430\u0437\u043d\u0430\u0447\u0435\u043d\u0438\u0435'),
        ),
        migrations.AlterField(
            model_name='ofice',
            name='entrance',
            field=models.IntegerField(blank=True, choices=[('\u0424\u0430\u0441\u0430\u0434', '\u0424\u0430\u0441\u0430\u0434'), ('\u0421\u043e \u0434\u0432\u043e\u0440\u0430', '\u0421\u043e \u0434\u0432\u043e\u0440\u0430'), ('\u0421 \u043f\u0430\u0440\u0430\u0434\u043d\u043e\u0439', '\u0421 \u043f\u0430\u0440\u0430\u0434\u043d\u043e\u0439')], null=True, verbose_name='\u0412\u0445\u043e\u0434'),
        ),
        migrations.AlterField(
            model_name='ofice',
            name='floor',
            field=models.CharField(blank=True, choices=[('1-\u0439', '1-\u0439'), ('\u0426\u043e\u043a\u043e\u043b\u044c', '\u0426\u043e\u043a\u043e\u043b\u044c'), ('\u0411\u0435\u043b\u044c\u044d\u0442\u0430\u0436', '\u0411\u0435\u043b\u044c\u044d\u0442\u0430\u0436')], max_length=20, null=True, verbose_name='\u042d\u0442\u0430\u0436'),
        ),
        migrations.AlterField(
            model_name='ofice',
            name='location',
            field=models.CharField(blank=True, choices=[('\u0424\u0430\u0441\u0430\u0434', '\u0424\u0430\u0441\u0430\u0434'), ('\u0414\u0432\u043e\u0440\u043e\u0432\u043e\u0439', '\u0414\u0432\u043e\u0440\u043e\u0432\u043e\u0439'), ('\u0411\u0438\u0437\u043d\u0435\u0441-\u0446\u0435\u043d\u0442\u0440', '\u0411\u0438\u0437\u043d\u0435\u0441-\u0446\u0435\u043d\u0442\u0440')], max_length=20, null=True, verbose_name='\u0420\u0430\u0441\u043f\u043e\u043b\u043e\u0436\u0435\u043d\u0438\u0435'),
        ),
        migrations.AlterField(
            model_name='ofice',
            name='status',
            field=models.CharField(blank=True, choices=[('VIP', 'VIP'), ('\u041e\u0431\u044b\u0447\u043d\u043e\u0435', '\u041e\u0431\u044b\u0447\u043d\u043e\u0435'), ('\u041a\u0440\u0430\u0442\u043a\u043e\u0435', '\u041a\u0440\u0430\u0442\u043a\u043e\u0435')], max_length=20, null=True, verbose_name='\u0421\u0442\u0430\u0442\u0443\u0441'),
        ),
        migrations.AlterField(
            model_name='ofice',
            name='type_deal',
            field=models.CharField(blank=True, choices=[('\u0410\u0440\u0435\u043d\u0434\u0430', '\u0410\u0440\u0435\u043d\u0434\u0430'), ('\u041f\u0440\u043e\u0434\u0430\u0436\u0430', '\u041f\u0440\u043e\u0434\u0430\u0436\u0430')], max_length=20, null=True, verbose_name='\u0422\u0438\u043f'),
        ),
    ]
