# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rieltor_object', '0021_auto_20170420_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ofice',
            name='entrance',
            field=models.CharField(blank=True, choices=[('\u0424\u0430\u0441\u0430\u0434', '\u0424\u0430\u0441\u0430\u0434'), ('\u0421\u043e \u0434\u0432\u043e\u0440\u0430', '\u0421\u043e \u0434\u0432\u043e\u0440\u0430'), ('\u0421 \u043f\u0430\u0440\u0430\u0434\u043d\u043e\u0439', '\u0421 \u043f\u0430\u0440\u0430\u0434\u043d\u043e\u0439')], max_length=20, null=True, verbose_name='\u0412\u0445\u043e\u0434'),
        ),
    ]
