# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-09 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rieltor_object', '0021_auto_20170609_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='sessons',
            field=models.CharField(blank=True, choices=[('low', '\u041d\u0438\u0437\u043a\u0438\u0439 \u0441\u0435\u0437\u043e\u043d'), ('up', '\u0412\u044b\u0441\u043e\u043a\u0438\u0439 \u0441\u0435\u0437\u043e\u043d'), ('pic', '\u041f\u0438\u043a \u0441\u0435\u0437\u043e\u043d\u0430')], max_length=50, null=True, verbose_name='\u0421\u0435\u0437\u043e\u043d'),
        ),
        migrations.AlterField(
            model_name='building',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='\u0426\u0435\u043d\u0430 \u0414\u043e\u043b\u0433\u043e\u0441\u0440\u043e\u0447\u043d\u0430\u044f'),
        ),
        migrations.AlterField(
            model_name='building',
            name='price_short',
            field=models.IntegerField(blank=True, null=True, verbose_name='\u0426\u0435\u043d\u0430 \u043c\u0435\u0441\u044f\u0446'),
        ),
    ]
