# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rieltor_object', '0022_auto_20170420_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infrastructure',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='infrastructure',
            name='object_id',
        ),
        migrations.AddField(
            model_name='newbuilding',
            name='infrastructures',
            field=models.ManyToManyField(related_name='newbuilding', to='rieltor_object.Infrastructure'),
        ),
    ]
