# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-29 16:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rieltor_object', '0023_auto_20170609_1545'),
        ('rieltor_object', '0023_auto_20170729_1459'),
    ]

    operations = [
    ]
