# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 22:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rieltor_object', '0023_auto_20170421_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newbuilding',
            name='infrastructures',
            field=models.ManyToManyField(blank=True, related_name='newbuilding', to='rieltor_object.Infrastructure'),
        ),
    ]
