# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 23:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rieltor_object', '0024_auto_20170421_0143'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='infrastructure',
            options={'ordering': ['-id'], 'verbose_name': '\u0418\u043d\u0444\u0440\u0430\u0441\u0442\u0440\u0443\u043a\u0442\u0443\u0440\u0430', 'verbose_name_plural': '\u0418\u043d\u0444\u0440\u0430\u0441\u0442\u0440\u0443\u043a\u0442\u0443\u0440\u0430'},
        ),
        migrations.RemoveField(
            model_name='accommodations',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='accommodations',
            name='object_id',
        ),
        migrations.AddField(
            model_name='newbuilding',
            name='accommodations',
            field=models.ManyToManyField(blank=True, related_name='newbuilding', to='rieltor_object.Accommodations'),
        ),
    ]
