# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rieltor_object', '0025_auto_20170421_0254'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApartmentHas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
            ],
            options={
                'verbose_name': '\u0412 \u043a\u0432\u0430\u0440\u0442\u0438\u0440\u0435 \u0435\u0441\u0442\u044c',
                'verbose_name_plural': '\u0412 \u043a\u0432\u0430\u0440\u0442\u0438\u0440\u0435 \u0435\u0441\u0442\u044c',
            },
        ),
        migrations.CreateModel(
            name='ApartmentNext',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('value', models.IntegerField(verbose_name='\u0417\u043d\u0430\u0447\u0435\u043d\u0438\u0435')),
            ],
            options={
                'verbose_name': '\u0420\u044f\u0434\u043e\u043c \u0441 \u043a\u0432\u0430\u0440\u0442\u0438\u0440\u043e\u0439',
                'verbose_name_plural': '\u0420\u044f\u0434\u043e\u043c \u0441 \u043a\u0432\u0430\u0440\u0442\u0438\u0440\u043e\u0439',
            },
        ),
        migrations.CreateModel(
            name='DailyDistrict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
            ],
            options={
                'verbose_name': '\u0420\u0430\u0439\u043e\u043d \u0434\u043b\u044f \u043f\u043e\u0441\u0443\u0442\u043e\u0447\u043d\u043e',
                'verbose_name_plural': '\u0420\u0430\u0439\u043e\u043d\u044b \u0434\u043b\u044f \u043f\u043e\u0441\u0443\u0442\u043e\u0447\u043d\u043e',
            },
        ),
        migrations.AlterField(
            model_name='accommodations',
            name='description',
            field=models.CharField(max_length=250, verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435'),
        ),
    ]
