# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rieltor_object', '0027_daily'),
    ]

    operations = [
        migrations.AddField(
            model_name='daily',
            name='point',
            field=models.IntegerField(blank=True, null=True, verbose_name='\u0411\u0430\u043b\u044b'),
        ),
    ]
