# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rieltor_object', '0028_daily_point'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daily',
            name='accommodations',
        ),
        migrations.AddField(
            model_name='daily',
            name='infrastructures',
            field=models.ManyToManyField(blank=True, related_name='daily', to='rieltor_object.Infrastructure'),
        ),
    ]
