# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 12:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('rieltor_object', '0029_auto_20170424_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daily',
            name='apartment_next',
        ),
        migrations.AddField(
            model_name='apartmentnext',
            name='content_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apartmentnext',
            name='object_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
