# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 22:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rieltor_object', '0031_auto_20170424_1648'),
    ]

    operations = [
        migrations.CreateModel(
            name='Communications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('communication', models.CharField(choices=[('\u0412\u043e\u0434\u0430', '\u0412\u043e\u0434\u0430'), ('\u0413\u0430\u0437', '\u0413\u0430\u0437'), ('\u041a\u0430\u043d\u0430\u043b\u0438\u0437\u0430\u0446\u0438\u044f', '\u041a\u0430\u043d\u0430\u043b\u0438\u0437\u0430\u0446\u0438\u044f'), ('\u042d\u043b\u0435\u043a\u0442\u0440\u0438\u0447\u0435\u0441\u0442\u0432\u043e', '\u042d\u043b\u0435\u043a\u0442\u0440\u0438\u0447\u0435\u0441\u0442\u0432\u043e')], max_length=50, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
            ],
            options={
                'verbose_name': '\u041a\u043e\u043c\u043c\u0443\u043d\u0438\u043a\u0430\u0446\u0438\u0438',
                'verbose_name_plural': '\u041a\u043e\u043c\u043c\u0443\u043d\u0438\u043a\u0430\u0446\u0438\u0438',
            },
        ),
        migrations.CreateModel(
            name='EarthDistrict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
            ],
            options={
                'verbose_name': '\u0420\u0430\u0439\u043e\u043d \u0434\u043b\u044f \u0437\u0435\u043c\u043b\u044f',
                'verbose_name_plural': '\u0420\u0430\u0439\u043e\u043d\u044b \u0434\u043b\u044f \u0437\u0435\u043c\u043b\u044f',
            },
        ),
        migrations.CreateModel(
            name='StructureHouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('communication', models.CharField(choices=[('\u0414\u043e\u043c', '\u0414\u043e\u043c'), ('\u041b\u0435\u0442\u043d\u0430\u044f \u043a\u0443\u0445\u043d\u044f', '\u041b\u0435\u0442\u043d\u0430\u044f \u043a\u0443\u0445\u043d\u044f'), ('\u0421\u0430\u0440\u0430\u0439', '\u0421\u0430\u0440\u0430\u0439'), ('\u0411\u0430\u0441\u0441\u0435\u0439\u043d', '\u0411\u0430\u0441\u0441\u0435\u0439\u043d')], max_length=50, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
            ],
            options={
                'verbose_name': '\u0421\u0442\u0440\u043e\u0435\u043d\u0438\u0435 \u0434\u043e\u043c\u0430',
                'verbose_name_plural': '\u0421\u0442\u0440\u043e\u0435\u043d\u0438\u0435 \u0434\u043e\u043c\u0430',
            },
        ),
        migrations.AlterField(
            model_name='daily',
            name='apartment_has',
            field=models.ManyToManyField(blank=True, help_text='\u0414\u043b\u044f \u0441\u043e\u0437\u0434\u0430\u043d\u0438\u044f \u0437\u043d\u0430\u0447\u0435\u043d\u0438\u044f \u043d\u0430\u0447\u043d\u0438\u0442\u0435 \u043d\u0430\u0431\u0438\u0440\u0430\u0442\u044c \u0442\u0435\u043a\u0441\u0442', related_name='daily', to='rieltor_object.ApartmentHas', verbose_name='\u0412 \u043a\u0432\u0430\u0440\u0442\u0438\u0440\u0435 \u0435\u0441\u0442\u044c'),
        ),
    ]
