# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 23:35
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rieltor_object', '0033_earth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communications',
            name='communication',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('\u0412\u043e\u0434\u0430', '\u0412\u043e\u0434\u0430'), ('\u0413\u0430\u0437', '\u0413\u0430\u0437'), ('\u041a\u0430\u043d\u0430\u043b\u0438\u0437\u0430\u0446\u0438\u044f', '\u041a\u0430\u043d\u0430\u043b\u0438\u0437\u0430\u0446\u0438\u044f'), ('\u042d\u043b\u0435\u043a\u0442\u0440\u0438\u0447\u0435\u0441\u0442\u0432\u043e', '\u042d\u043b\u0435\u043a\u0442\u0440\u0438\u0447\u0435\u0441\u0442\u0432\u043e')], max_length=50, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435'),
        ),
        migrations.AlterField(
            model_name='structurehouse',
            name='communication',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('\u0414\u043e\u043c', '\u0414\u043e\u043c'), ('\u041b\u0435\u0442\u043d\u0430\u044f \u043a\u0443\u0445\u043d\u044f', '\u041b\u0435\u0442\u043d\u0430\u044f \u043a\u0443\u0445\u043d\u044f'), ('\u0421\u0430\u0440\u0430\u0439', '\u0421\u0430\u0440\u0430\u0439'), ('\u0411\u0430\u0441\u0441\u0435\u0439\u043d', '\u0411\u0430\u0441\u0441\u0435\u0439\u043d')], max_length=50, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435'),
        ),
    ]
