# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 23:38
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rieltor_object', '0035_auto_20170425_0237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earth',
            name='communication',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('\u0412\u043e\u0434\u0430', '\u0412\u043e\u0434\u0430'), ('\u0413\u0430\u0437', '\u0413\u0430\u0437'), ('\u041a\u0430\u043d\u0430\u043b\u0438\u0437\u0430\u0446\u0438\u044f', '\u041a\u0430\u043d\u0430\u043b\u0438\u0437\u0430\u0446\u0438\u044f'), ('\u042d\u043b\u0435\u043a\u0442\u0440\u0438\u0447\u0435\u0441\u0442\u0432\u043e', '\u042d\u043b\u0435\u043a\u0442\u0440\u0438\u0447\u0435\u0441\u0442\u0432\u043e')], max_length=50, null=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435'),
        ),
    ]
