# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 23:47
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rieltor_object', '0037_auto_20170425_0245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='earth',
            name='structure_house',
        ),
        migrations.AddField(
            model_name='earth',
            name='structure_house',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('\u0414\u043e\u043c', '\u0414\u043e\u043c'), ('\u041b\u0435\u0442\u043d\u0430\u044f \u043a\u0443\u0445\u043d\u044f', '\u041b\u0435\u0442\u043d\u0430\u044f \u043a\u0443\u0445\u043d\u044f'), ('\u0421\u0430\u0440\u0430\u0439', '\u0421\u0430\u0440\u0430\u0439'), ('\u0411\u0430\u0441\u0441\u0435\u0439\u043d', '\u0411\u0430\u0441\u0441\u0435\u0439\u043d')], max_length=50, null=True, verbose_name='\u0421\u0442\u0440\u043e\u0435\u043d\u0438\u0435 \u0434\u043e\u043c\u0430'),
        ),
        migrations.DeleteModel(
            name='StructureHouse',
        ),
    ]
