# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 02:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rieltor_object', '0038_auto_20170425_0247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earth',
            name='to_city',
            field=models.IntegerField(blank=True, null=True, verbose_name='\u0414\u043e \u0433\u043e\u0440\u043e\u0434\u0430, \u043a\u043c'),
        ),
    ]
