# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rieltor_object', '0040_auto_20170505_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='newbuilding',
            name='price_object',
            field=models.IntegerField(blank=True, null=True, verbose_name='\u0426\u0435\u043d\u0430 \u0437\u0430 \u043e\u0431\u044a\u0435\u043a\u0442'),
        ),
    ]
