# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 00:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rieltor_object', '0039_auto_20170425_0550'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('buildings', models.ManyToManyField(blank=True, related_name='favorites', to='rieltor_object.Building')),
                ('dailys', models.ManyToManyField(blank=True, related_name='favorites', to='rieltor_object.Daily')),
                ('earth', models.ManyToManyField(blank=True, related_name='favorites', to='rieltor_object.Earth')),
                ('newbuildings', models.ManyToManyField(blank=True, related_name='favorites', to='rieltor_object.NewBuilding')),
                ('offices', models.ManyToManyField(blank=True, related_name='favorites', to='rieltor_object.Ofice')),
            ],
        ),
    ]
