# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 03:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import services.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cleaning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(allow_unicode=True, default='\u0443\u0431\u043e\u0440\u043a\u0430-\u043a\u0432\u0430\u0440\u0442\u0438\u0440', validators=[services.models.slug_validator], verbose_name='URL')),
                ('title', models.CharField(blank=True, max_length=250, null=True, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a')),
                ('SEOTitle', models.TextField(blank=True, null=True, verbose_name='SEO Title')),
                ('SEOKeywords', models.TextField(blank=True, null=True, verbose_name='SEO Keywords')),
                ('SEODescription', models.TextField(blank=True, null=True, verbose_name='SEO Description')),
                ('image', models.ImageField(blank=True, upload_to='services/%Y/%m/%d/', verbose_name='\u0424\u043e\u0442\u043e')),
                ('is_enable', models.BooleanField(default=True, verbose_name='\u0412\u043b\u044e\u0447\u0435\u043d \u043b\u0438?')),
                ('packet_enable', models.BooleanField(default=True, verbose_name='\u0412\u043b\u044e\u0447\u0435\u043d \u043b\u0438 \u043f\u0430\u043a\u0435\u0442?')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('base_packet', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='cleaning', to='common.BasePacket', verbose_name='\u041f\u0430\u043a\u0435\u0442 \u043d\u0430\u0447\u0438\u043d\u0430\u044e\u0449\u0438\u0439')),
                ('expert_packet', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='cleaning', to='common.ExpertPacket', verbose_name='\u041f\u0430\u043a\u0435\u0442 \u042d\u043a\u0441\u043f\u0435\u0440\u0442')),
                ('midle_packet', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='cleaning', to='common.MidlePacket', verbose_name='\u041f\u0430\u043a\u0435\u0442 \u041f\u0440\u043e\u0434\u0432\u0438\u043d\u0443\u0442\u044b\u0439')),
            ],
            options={
                'verbose_name': '\u0423\u0431\u043e\u0440\u043a\u0430 \u043a\u0432\u0430\u0440\u0442\u0438\u0440',
            },
        ),
        migrations.CreateModel(
            name='InstallationWater',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(allow_unicode=True, default='\u0443\u0441\u0442\u0430\u043d\u043e\u0432\u043a\u0430-\u0432\u043e\u0434\u043e\u043c\u0435\u0440\u0430', validators=[services.models.slug_validator], verbose_name='URL')),
                ('title', models.CharField(blank=True, max_length=250, null=True, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a')),
                ('subtitle', models.CharField(blank=True, max_length=250, null=True, verbose_name='\u041f\u043e\u0434\u0437\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a')),
                ('SEOTitle', models.TextField(blank=True, null=True, verbose_name='SEO Title')),
                ('SEOKeywords', models.TextField(blank=True, null=True, verbose_name='SEO Keywords')),
                ('SEODescription', models.TextField(blank=True, null=True, verbose_name='SEO Description')),
                ('image', models.ImageField(blank=True, upload_to='services/%Y/%m/%d/', verbose_name='\u0424\u043e\u0442\u043e')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('is_enable', models.BooleanField(default=True, verbose_name='\u0412\u043b\u044e\u0447\u0435\u043d \u043b\u0438?')),
                ('packet_enable', models.BooleanField(default=True, verbose_name='\u0412\u043b\u044e\u0447\u0435\u043d \u043b\u0438 \u043f\u0430\u043a\u0435\u0442?')),
                ('faq_enable', models.BooleanField(default=True, verbose_name='\u0412\u043b\u044e\u0447\u0435\u043d \u043b\u0438 FAQ?')),
                ('base_packet', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='installation_water', to='common.BasePacket', verbose_name='\u041f\u0430\u043a\u0435\u0442 \u043d\u0430\u0447\u0438\u043d\u0430\u044e\u0449\u0438\u0439')),
                ('expert_packet', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='installation_water', to='common.ExpertPacket', verbose_name='\u041f\u0430\u043a\u0435\u0442 \u042d\u043a\u0441\u043f\u0435\u0440\u0442')),
                ('midle_packet', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='installation_water', to='common.MidlePacket', verbose_name='\u041f\u0430\u043a\u0435\u0442 \u041f\u0440\u043e\u0434\u0432\u0438\u043d\u0443\u0442\u044b\u0439')),
            ],
            options={
                'verbose_name': '\u0423\u0441\u0442\u0430\u043d\u043e\u0432\u043a\u0430 \u0432\u043e\u0434\u043e\u043c\u0435\u0440\u0430',
            },
        ),
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(allow_unicode=True, default='\u0441\u0442\u0440\u0430\u0445\u043e\u0432\u0430\u043d\u0438\u0435-\u043d\u0435\u0434\u0432\u0438\u0436\u0438\u043c\u043e\u0441\u0442\u0438', validators=[services.models.slug_validator], verbose_name='URL')),
                ('title', models.CharField(blank=True, max_length=250, null=True, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a')),
                ('SEOTitle', models.TextField(blank=True, null=True, verbose_name='SEO Title')),
                ('SEOKeywords', models.TextField(blank=True, null=True, verbose_name='SEO Keywords')),
                ('SEODescription', models.TextField(blank=True, null=True, verbose_name='SEO Description')),
                ('image', models.ImageField(blank=True, upload_to='services/%Y/%m/%d/', verbose_name='\u0424\u043e\u0442\u043e')),
                ('is_enable', models.BooleanField(default=True, verbose_name='\u0412\u043b\u044e\u0447\u0435\u043d \u043b\u0438?')),
                ('faq_enable', models.BooleanField(default=True, verbose_name='\u0412\u043b\u044e\u0447\u0435\u043d \u043b\u0438 FAQ?')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
            ],
            options={
                'verbose_name': '\u0421\u0442\u0440\u0430\u0445\u043e\u0432\u0430\u043d\u0438\u0435 \u043d\u0435\u0434\u0432\u0438\u0436\u0438\u043c\u043e\u0441\u0442\u0438',
            },
        ),
        migrations.CreateModel(
            name='Repair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(allow_unicode=True, default='\u0440\u0435\u043c\u043e\u043d\u0442-\u043f\u043e\u043c\u0435\u0449\u0435\u043d\u0438\u044f', validators=[services.models.slug_validator], verbose_name='URL')),
                ('title', models.CharField(blank=True, max_length=250, null=True, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a')),
                ('subtitle', models.CharField(blank=True, max_length=250, null=True, verbose_name='\u041f\u043e\u0434\u0437\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a')),
                ('help_subtitle', models.CharField(blank=True, max_length=250, null=True, verbose_name='\u041f\u043e\u0434-\u043f\u043e\u0434-\u0437\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a')),
                ('SEOTitle', models.TextField(blank=True, null=True, verbose_name='SEO Title')),
                ('SEOKeywords', models.TextField(blank=True, null=True, verbose_name='SEO Keywords')),
                ('SEODescription', models.TextField(blank=True, null=True, verbose_name='SEO Description')),
                ('image', models.ImageField(blank=True, upload_to='services/%Y/%m/%d/', verbose_name='\u0424\u043e\u0442\u043e')),
                ('is_enable', models.BooleanField(default=True, verbose_name='\u0412\u043b\u044e\u0447\u0435\u043d \u043b\u0438?')),
                ('faq_enable', models.BooleanField(default=True, verbose_name='\u0412\u043b\u044e\u0447\u0435\u043d \u043b\u0438 FAQ?')),
                ('image_enable', models.BooleanField(default=True, verbose_name='\u0412\u043b\u044e\u0447\u0435\u043d\u0438 \u043b\u0438 \u0444\u043e\u0442\u043e?')),
                ('repairs_enable', models.BooleanField(default=True, verbose_name='\u0412\u043b\u044e\u0447\u0435\u043d\u0430 \u043b\u0438 \u0421\u0442\u043e\u0438\u043c\u043e\u0441\u0442\u044c \u0440\u0435\u043c\u043e\u043d\u0442\u0430?')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
            ],
            options={
                'verbose_name': '\u0420\u0435\u043c\u043e\u043d\u0442 \u043f\u043e\u043c\u0435\u0449\u0435\u043d\u0438\u044f',
            },
        ),
        migrations.CreateModel(
            name='ServicesRieltor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(allow_unicode=True, default='\u0443\u0441\u043b\u0443\u0433\u0438-\u0440\u0438\u0435\u043b\u0442\u043e\u0440\u0441\u043a\u0438\u0435', validators=[services.models.slug_validator], verbose_name='URL')),
                ('title', models.CharField(blank=True, max_length=250, null=True, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a')),
                ('SEOTitle', models.TextField(blank=True, null=True, verbose_name='SEO Title')),
                ('SEOKeywords', models.TextField(blank=True, null=True, verbose_name='SEO Keywords')),
                ('SEODescription', models.TextField(blank=True, null=True, verbose_name='SEO Description')),
                ('image', models.ImageField(blank=True, upload_to='services/%Y/%m/%d/', verbose_name='\u0424\u043e\u0442\u043e')),
                ('is_enable', models.BooleanField(default=True, verbose_name='\u0412\u043b\u044e\u0447\u0435\u043d \u043b\u0438?')),
                ('faq_enable', models.BooleanField(default=True, verbose_name='\u0412\u043b\u044e\u0447\u0435\u043d \u043b\u0438 FAQ?')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
            ],
            options={
                'verbose_name': '\u0423\u0441\u043b\u0443\u0433\u0438 \u0440\u0438\u0435\u043b\u0442\u043e\u0440\u0441\u043a\u0438\u0435',
            },
        ),
        migrations.CreateModel(
            name='UniversalService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(allow_unicode=True, unique=True, validators=[services.models.slug_validator], verbose_name='URL')),
                ('name', models.CharField(max_length=250, unique=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('title', models.CharField(blank=True, max_length=250, null=True, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a')),
                ('SEOTitle', models.TextField(blank=True, null=True, verbose_name='SEO Title')),
                ('SEOKeywords', models.TextField(blank=True, null=True, verbose_name='SEO Keywords')),
                ('SEODescription', models.TextField(blank=True, null=True, verbose_name='SEO Description')),
                ('image', models.ImageField(blank=True, upload_to='services/%Y/%m/%d/', verbose_name='\u0424\u043e\u0442\u043e')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('is_enable', models.BooleanField(default=True, verbose_name='\u0412\u043b\u044e\u0447\u0435\u043d \u043b\u0438?')),
                ('packet_enable', models.BooleanField(default=True, verbose_name='\u0412\u043b\u044e\u0447\u0435\u043d \u043b\u0438 \u043f\u0430\u043a\u0435\u0442?')),
                ('faq_enable', models.BooleanField(default=True, verbose_name='\u0412\u043b\u044e\u0447\u0435\u043d \u043b\u0438 FAQ?')),
                ('base_packet', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='universal', to='common.BasePacket', verbose_name='\u041f\u0430\u043a\u0435\u0442 \u043d\u0430\u0447\u0438\u043d\u0430\u044e\u0449\u0438\u0439')),
                ('expert_packet', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='installation_water', to='common.ExpertPacket', verbose_name='\u041f\u0430\u043a\u0435\u0442 \u042d\u043a\u0441\u043f\u0435\u0440\u0442')),
                ('midle_packet', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='universal', to='common.MidlePacket', verbose_name='\u041f\u0430\u043a\u0435\u0442 \u041f\u0440\u043e\u0434\u0432\u0438\u043d\u0443\u0442\u044b\u0439')),
            ],
            options={
                'ordering': ['id'],
                'verbose_name': '\u0423\u043d\u0438\u0432\u0435\u0440\u0441\u0430\u043b\u044c\u043d\u0430\u044f \u0443\u0441\u043b\u0443\u0433\u0430',
                'verbose_name_plural': '\u0423\u043d\u0438\u0432\u0435\u0440\u0441\u0430\u043b\u044c\u043d\u0438\u0435 \u0443\u0441\u043b\u0443\u0433\u0438',
            },
        ),
        migrations.CreateModel(
            name='Valuation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(allow_unicode=True, default='\u043e\u0446\u0435\u043d\u043a\u0430-\u043d\u0435\u0434\u0432\u0438\u0436\u0438\u043c\u043e\u0441\u0442\u0438', validators=[services.models.slug_validator], verbose_name='URL')),
                ('title', models.CharField(blank=True, max_length=250, null=True, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a')),
                ('SEOTitle', models.TextField(blank=True, null=True, verbose_name='SEO Title')),
                ('SEOKeywords', models.TextField(blank=True, null=True, verbose_name='SEO Keywords')),
                ('SEODescription', models.TextField(blank=True, null=True, verbose_name='SEO Description')),
                ('image', models.ImageField(blank=True, upload_to='services/%Y/%m/%d/', verbose_name='\u0424\u043e\u0442\u043e')),
                ('is_enable', models.BooleanField(default=True, verbose_name='\u0412\u043b\u044e\u0447\u0435\u043d \u043b\u0438?')),
                ('faq_enable', models.BooleanField(default=True, verbose_name='\u0412\u043b\u044e\u0447\u0435\u043d \u043b\u0438 FAQ?')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
            ],
            options={
                'verbose_name': '\u041e\u0446\u0435\u043d\u043a\u0430 \u043d\u0435\u0434\u0432\u0438\u0436\u0438\u043c\u043e\u0441\u0442\u0438',
            },
        ),
    ]
