# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicesrieltor',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, default='\u0423\u0441\u043b\u0443\u0433\u0438 \u0440\u0438\u0435\u043b\u0442\u043e\u0440\u0441\u043a\u0438\u0435', null=True, unique=True, verbose_name='URL'),
        ),
    ]
