# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleaning',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435 \u0433\u043b\u0430\u0432\u043d\u0430\u044f \u0443\u0441\u043b\u0443\u0433\u0438'),
        ),
        migrations.AddField(
            model_name='installationwater',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435 \u0433\u043b\u0430\u0432\u043d\u0430\u044f \u0443\u0441\u043b\u0443\u0433\u0438'),
        ),
        migrations.AddField(
            model_name='insurance',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435 \u0433\u043b\u0430\u0432\u043d\u0430\u044f \u0443\u0441\u043b\u0443\u0433\u0438'),
        ),
        migrations.AddField(
            model_name='repair',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435 \u0433\u043b\u0430\u0432\u043d\u0430\u044f \u0443\u0441\u043b\u0443\u0433\u0438'),
        ),
        migrations.AddField(
            model_name='servicesrieltor',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435 \u0433\u043b\u0430\u0432\u043d\u0430\u044f \u0443\u0441\u043b\u0443\u0433\u0438'),
        ),
        migrations.AddField(
            model_name='universalservice',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435 \u0433\u043b\u0430\u0432\u043d\u0430\u044f \u0443\u0441\u043b\u0443\u0433\u0438'),
        ),
        migrations.AddField(
            model_name='valuation',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435 \u0433\u043b\u0430\u0432\u043d\u0430\u044f \u0443\u0441\u043b\u0443\u0433\u0438'),
        ),
    ]
