# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 01:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicesrieltor',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='\u0412\u043b\u044e\u0447\u0435\u043d \u043b\u0438?'),
        ),
    ]
