# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-11 22:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20170507_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleaning',
            name='image_avatar',
            field=models.ImageField(blank=True, upload_to='services/%Y/%m/%d/', verbose_name='\u0424\u043e\u0442\u043e \u0430\u0432\u0430\u0442\u0430\u0440'),
        ),
        migrations.AddField(
            model_name='installationwater',
            name='image_avatar',
            field=models.ImageField(blank=True, upload_to='services/%Y/%m/%d/', verbose_name='\u0424\u043e\u0442\u043e \u0430\u0432\u0430\u0442\u0430\u0440'),
        ),
        migrations.AddField(
            model_name='insurance',
            name='image_avatar',
            field=models.ImageField(blank=True, upload_to='services/%Y/%m/%d/', verbose_name='\u0424\u043e\u0442\u043e \u0430\u0432\u0430\u0442\u0430\u0440'),
        ),
        migrations.AddField(
            model_name='repair',
            name='image_avatar',
            field=models.ImageField(blank=True, upload_to='services/%Y/%m/%d/', verbose_name='\u0424\u043e\u0442\u043e \u0430\u0432\u0430\u0442\u0430\u0440'),
        ),
        migrations.AddField(
            model_name='servicesrieltor',
            name='image_avatar',
            field=models.ImageField(blank=True, upload_to='services/%Y/%m/%d/', verbose_name='\u0424\u043e\u0442\u043e \u0430\u0432\u0430\u0442\u0430\u0440'),
        ),
        migrations.AddField(
            model_name='universalservice',
            name='image_avatar',
            field=models.ImageField(blank=True, upload_to='services/%Y/%m/%d/', verbose_name='\u0424\u043e\u0442\u043e \u0430\u0432\u0430\u0442\u0430\u0440'),
        ),
        migrations.AddField(
            model_name='valuation',
            name='image_avatar',
            field=models.ImageField(blank=True, upload_to='services/%Y/%m/%d/', verbose_name='\u0424\u043e\u0442\u043e \u0430\u0432\u0430\u0442\u0430\u0440'),
        ),
    ]
