# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 19:03
from __future__ import unicode_literals

from django.db import migrations, models
import services.models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20170331_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicesrieltor',
            name='slug',
            field=models.SlugField(allow_unicode=True, default='\u0443\u0441\u043b\u0443\u0433\u0438-\u0440\u0438\u0435\u043b\u0442\u043e\u0440\u0441\u043a\u0438\u0435', validators=[services.models.slug_validator], verbose_name='URL'),
        ),
    ]
