# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 23:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_auto_20170331_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicesrieltor',
            name='faq_enable',
            field=models.BooleanField(default=True, verbose_name='\u0412\u043b\u044e\u0447\u0435\u043d \u043b\u0438 FAQ?'),
        ),
    ]
