# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-12 11:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20170512_0440'),
        ('services', '0004_auto_20170512_0318'),
    ]

    operations = [
    ]
