# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-25 02:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_partner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partner',
            options={'verbose_name': '\u041f\u0430\u0440\u0442\u043d\u0435\u0440', 'verbose_name_plural': '\u041f\u0430\u0440\u0442\u043d\u0435\u0440\u0438'},
        ),
    ]
