# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 01:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_auto_20170525_0543'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicesrieltor',
            name='name',
            field=models.CharField(blank=True, default='\u0423\u0441\u043b\u0443\u0433\u0438 \u0440\u0438\u0435\u043b\u0442\u043e\u0440\u0441\u043a\u0438\u0435', max_length=250, null=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435'),
        ),
    ]
