# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_repair_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='repair',
            name='help_subtitle',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='\u041f\u043e\u0434-\u043f\u043e\u0434-\u0437\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a'),
        ),
        migrations.AddField(
            model_name='repair',
            name='subtitle',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='\u041f\u043e\u0434\u0437\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a'),
        ),
    ]
