# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 01:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_servicesrieltor_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleaning',
            name='name',
            field=models.CharField(blank=True, default='\u0423\u0431\u043e\u0440\u043a\u0430 \u043a\u0432\u0430\u0440\u0442\u0438\u0440', max_length=250, null=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435'),
        ),
        migrations.AddField(
            model_name='installationwater',
            name='name',
            field=models.CharField(blank=True, default='\u0423\u0441\u0442\u0430\u043d\u043e\u0432\u043a\u0430 \u0432\u043e\u0434\u043e\u043c\u0435\u0440\u0430', max_length=250, null=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435'),
        ),
        migrations.AddField(
            model_name='insurance',
            name='name',
            field=models.CharField(blank=True, default='\u0421\u0442\u0440\u0430\u0445\u043e\u0432\u0430\u043d\u0438\u0435 \u043d\u0435\u0434\u0432\u0438\u0436\u0438\u043c\u043e\u0441\u0442\u0438', max_length=250, null=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435'),
        ),
        migrations.AddField(
            model_name='repair',
            name='name',
            field=models.CharField(blank=True, default='\u0420\u0435\u043c\u043e\u043d\u0442 \u043f\u043e\u043c\u0435\u0449\u0435\u043d\u0438\u044f', max_length=250, null=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435'),
        ),
        migrations.AddField(
            model_name='valuation',
            name='name',
            field=models.CharField(blank=True, default='\u041e\u0446\u0435\u043d\u043a\u0430 \u043d\u0435\u0434\u0432\u0438\u0436\u0438\u043c\u043e\u0441\u0442\u0438', max_length=250, null=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435'),
        ),
    ]
