# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 01:03
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_auto_20170529_0412'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleaning',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='\u041a\u043e\u043d\u0442\u0435\u043d\u0442'),
        ),
        migrations.AddField(
            model_name='cleaning',
            name='image_seo',
            field=models.ImageField(blank=True, upload_to='seo/%Y/%m/%d/', verbose_name='\u0424\u043e\u0442\u043e'),
        ),
        migrations.AddField(
            model_name='cleaning',
            name='title_seo',
            field=models.TextField(blank=True, null=True, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a'),
        ),
        migrations.AddField(
            model_name='installationwater',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='\u041a\u043e\u043d\u0442\u0435\u043d\u0442'),
        ),
        migrations.AddField(
            model_name='installationwater',
            name='image_seo',
            field=models.ImageField(blank=True, upload_to='seo/%Y/%m/%d/', verbose_name='\u0424\u043e\u0442\u043e'),
        ),
        migrations.AddField(
            model_name='installationwater',
            name='title_seo',
            field=models.TextField(blank=True, null=True, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a'),
        ),
        migrations.AddField(
            model_name='insurance',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='\u041a\u043e\u043d\u0442\u0435\u043d\u0442'),
        ),
        migrations.AddField(
            model_name='insurance',
            name='image_seo',
            field=models.ImageField(blank=True, upload_to='seo/%Y/%m/%d/', verbose_name='\u0424\u043e\u0442\u043e'),
        ),
        migrations.AddField(
            model_name='insurance',
            name='title_seo',
            field=models.TextField(blank=True, null=True, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a'),
        ),
        migrations.AddField(
            model_name='repair',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='\u041a\u043e\u043d\u0442\u0435\u043d\u0442'),
        ),
        migrations.AddField(
            model_name='repair',
            name='image_seo',
            field=models.ImageField(blank=True, upload_to='seo/%Y/%m/%d/', verbose_name='\u0424\u043e\u0442\u043e'),
        ),
        migrations.AddField(
            model_name='repair',
            name='title_seo',
            field=models.TextField(blank=True, null=True, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a'),
        ),
        migrations.AddField(
            model_name='servicesrieltor',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='\u041a\u043e\u043d\u0442\u0435\u043d\u0442'),
        ),
        migrations.AddField(
            model_name='servicesrieltor',
            name='image_seo',
            field=models.ImageField(blank=True, upload_to='seo/%Y/%m/%d/', verbose_name='\u0424\u043e\u0442\u043e'),
        ),
        migrations.AddField(
            model_name='servicesrieltor',
            name='title_seo',
            field=models.TextField(blank=True, null=True, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a'),
        ),
        migrations.AddField(
            model_name='universalservice',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='\u041a\u043e\u043d\u0442\u0435\u043d\u0442'),
        ),
        migrations.AddField(
            model_name='universalservice',
            name='image_seo',
            field=models.ImageField(blank=True, upload_to='seo/%Y/%m/%d/', verbose_name='\u0424\u043e\u0442\u043e'),
        ),
        migrations.AddField(
            model_name='universalservice',
            name='title_seo',
            field=models.TextField(blank=True, null=True, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a'),
        ),
        migrations.AddField(
            model_name='valuation',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='\u041a\u043e\u043d\u0442\u0435\u043d\u0442'),
        ),
        migrations.AddField(
            model_name='valuation',
            name='image_seo',
            field=models.ImageField(blank=True, upload_to='seo/%Y/%m/%d/', verbose_name='\u0424\u043e\u0442\u043e'),
        ),
        migrations.AddField(
            model_name='valuation',
            name='title_seo',
            field=models.TextField(blank=True, null=True, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a'),
        ),
    ]
