# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-06 03:22
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_insurance'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurance',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
