# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-06 15:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import services.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_basepacket_textpacket'),
        ('services', '0011_insurance_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cleaning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(allow_unicode=True, default='\u0443\u0431\u043e\u0440\u043a\u0430-\u043a\u0432\u0430\u0440\u0442\u0438\u0440', validators=[services.models.slug_validator], verbose_name='URL')),
                ('title', models.CharField(blank=True, max_length=250, null=True, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a')),
                ('SEOTitle', models.TextField(blank=True, null=True, verbose_name='SEO Title')),
                ('SEOKeywords', models.TextField(blank=True, null=True, verbose_name='SEO Keywords')),
                ('SEODescription', models.TextField(blank=True, null=True, verbose_name='SEO Description')),
                ('image', models.ImageField(blank=True, upload_to='services/%Y/%m/%d/', verbose_name='\u0424\u043e\u0442\u043e')),
                ('is_enable', models.BooleanField(default=True, verbose_name='\u0412\u043b\u044e\u0447\u0435\u043d \u043b\u0438?')),
                ('packet_enable', models.BooleanField(default=True, verbose_name='\u0412\u043b\u044e\u0447\u0435\u043d \u043b\u0438 \u043f\u0430\u043a\u0435\u0442?')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('base_packet', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_query_name='valuation', to='common.BasePacket', verbose_name='\u041d\u0430\u0447\u0438\u043d\u0430\u044e\u0449\u0438\u0439')),
            ],
            options={
                'verbose_name': '\u0423\u0431\u043e\u0440\u043a\u0430 \u043a\u0432\u0430\u0440\u0442\u0438\u0440',
            },
        ),
    ]
