# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-08 13:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0013_auto_20170406_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleaning',
            name='base_packet',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_query_name='cleaning', to='common.BasePacket', verbose_name='\u041f\u0430\u043a\u0435\u0442 \u043d\u0430\u0447\u0438\u043d\u0430\u044e\u0449\u0438\u0439'),
        ),
        migrations.AlterField(
            model_name='cleaning',
            name='expert_packet',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_query_name='cleaning', to='common.ExpertPacket', verbose_name='\u041f\u0430\u043a\u0435\u0442 \u042d\u043a\u0441\u043f\u0435\u0440\u0442'),
        ),
        migrations.AlterField(
            model_name='cleaning',
            name='midle_packet',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_query_name='cleaning', to='common.MidlePacket', verbose_name='\u041f\u0430\u043a\u0435\u0442 \u041f\u0440\u043e\u0434\u0432\u0438\u043d\u0443\u0442\u044b\u0439'),
        ),
    ]
