# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-08 20:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0017_universalservice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='universalservice',
            options={'verbose_name': '\u0423\u043d\u0438\u0432\u0435\u0440\u0441\u0430\u043b\u044c\u043d\u0430\u044f \u0443\u0441\u043b\u0443\u0433\u0430', 'verbose_name_plural': '\u0423\u043d\u0438\u0432\u0435\u0440\u0441\u0430\u043b\u044c\u043d\u0438\u0435 \u0443\u0441\u043b\u0443\u0433\u0438'},
        ),
        migrations.AlterField(
            model_name='universalservice',
            name='base_packet',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='universal', to='common.BasePacket', verbose_name='\u041f\u0430\u043a\u0435\u0442 \u043d\u0430\u0447\u0438\u043d\u0430\u044e\u0449\u0438\u0439'),
        ),
        migrations.AlterField(
            model_name='universalservice',
            name='midle_packet',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='universal', to='common.MidlePacket', verbose_name='\u041f\u0430\u043a\u0435\u0442 \u041f\u0440\u043e\u0434\u0432\u0438\u043d\u0443\u0442\u044b\u0439'),
        ),
    ]
