# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-09 13:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0018_auto_20170408_2323'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='universalservice',
            options={'ordering': ['id'], 'verbose_name': '\u0423\u043d\u0438\u0432\u0435\u0440\u0441\u0430\u043b\u044c\u043d\u0430\u044f \u0443\u0441\u043b\u0443\u0433\u0430', 'verbose_name_plural': '\u0423\u043d\u0438\u0432\u0435\u0440\u0441\u0430\u043b\u044c\u043d\u0438\u0435 \u0443\u0441\u043b\u0443\u0433\u0438'},
        ),
    ]
