# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-28 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20170628_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlresult',
            name='slug',
            field=models.SlugField(allow_unicode=True, unique=True, verbose_name='URL'),
        ),
    ]
