# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20170501_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='polls',
            name='ball_from',
            field=models.IntegerField(default=1, verbose_name='\u0411\u0430\u043b\u043b\u043e\u0432 \u041e\u0442'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='polls',
            name='ball_to',
            field=models.IntegerField(default=1, verbose_name='\u0411\u0430\u043b\u043b\u043e\u0432 \u0414\u043e'),
            preserve_default=False,
        ),
    ]
