# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 23:20
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20170502_0024'),
    ]

    operations = [
        migrations.AddField(
            model_name='polls',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='\u041a\u043e\u043d\u0442\u0435\u043d\u0442'),
        ),
    ]
