# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seo',
            name='url',
            field=models.URLField(unique=True, verbose_name='URL'),
        ),
    ]
