# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-09 01:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seo',
            name='url',
            field=models.URLField(help_text='\u041f\u043e\u043b\u043d\u0438\u0439 \u043f\u0443\u0442\u044c. \u041f\u0440\u0438\u043c\u0435\u0440 http://example.com', unique=True, verbose_name='URL'),
        ),
    ]
