# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0002_auto_20170505_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='seo',
            name='image',
            field=models.ImageField(blank=True, upload_to='seo/%Y/%m/%d/', verbose_name='\u0424\u043e\u0442\u043e'),
        ),
    ]
