# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-15 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0002_auto_20170509_0403'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seo',
            old_name='content',
            new_name='content_seo',
        ),
        migrations.RenameField(
            model_name='seo',
            old_name='image',
            new_name='image_seo',
        ),
        migrations.RemoveField(
            model_name='seo',
            name='title_h1',
        ),
        migrations.AddField(
            model_name='seo',
            name='title_seo',
            field=models.TextField(blank=True, null=True, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a'),
        ),
        migrations.AlterField(
            model_name='seo',
            name='title',
            field=models.TextField(blank=True, null=True, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a H1'),
        ),
    ]
